In [1]:
import random
import cobra
import escher
import pandas as pd
import numpy as np
import json
import csv
from cobra.io import save_json_model
from cobra import Reaction
from collections import Counter
from cobra.flux_analysis.loopless import add_loopless, loopless_solution

In [2]:
cobra.Configuration().solver = "gurobi"

In [3]:
# model_path = './models/iMT1026v3.xml'
model_path = './models/iMT1026v3jup.xml'

model = cobra.io.read_sbml_model(model_path)

model

Set parameter Username
Academic license - for non-commercial use only - expires 2027-09-18

In [4]:
model.summary()

In [5]:
# Change grwoth on glycerol to growth on 60% glucose and 40% methanol
# Add reaction describing this growth

biomass_gly = model.reactions.get_by_id('BIOMASS_glyc')
biomass_gly.bounds = (0,0)
biomass_gly

carbs = model.metabolites.get_by_id('CARBOHYDRATES_c')
DNA = model.metabolites.get_by_id('DNA_c')
lipids = model.metabolites.get_by_id('LIPIDS_c')
prot = model.metabolites.get_by_id('PROTEIN_c')
RNA = model.metabolites.get_by_id('RNA_c')
atp = model.metabolites.get_by_id('atp_c')
cof = model.metabolites.get_by_id('cof_c')
h2o = model.metabolites.get_by_id('h2o_c')
adp = model.metabolites.get_by_id('adp_c')
biomass = model.metabolites.get_by_id('biomass_c')
h = model.metabolites.get_by_id('h_c')
pi = model.metabolites.get_by_id('pi_c')

biomass_glc_meoh = Reaction ('biomass_glc_meoh_60/40')
biomass_glc_meoh.name = 'Biomass composition (g/g) - 60/40 Glucose/Methanol'
biomass_glc_meoh.add_metabolites({carbs: -0.33,
                                   DNA: -0.001,
                                   lipids: -0.042,
                                   prot: -0.49,
                                   RNA: -0.058,
                                   atp: -63.85,
                                   cof: -1,
                                   h2o: -63.85,
                                   adp: 63.85,
                                   pi: 63.85,
                                   biomass: 1,
                                   h: 63.85})
biomass_glc_meoh

In [6]:
# Add new biomass reaction to the model

print (len(model.reactions))
model.add_reactions([biomass_glc_meoh])
print (len(model.reactions))

2237
2238

In [7]:
#Tanquem l'entrada de Glicerol
glycerol_exchange = model.exchanges.get_by_id('Ex_glyc')
glycerol_exchange.bounds = (0,0)
glycerol_exchange

In [8]:
# Add qmeoh constraints observed in chemostat cultivations
methanol_exchange = model.exchanges.get_by_id('Ex_meoh')
methanol_exchange.bounds = (-1.24, -1.18)
methanol_exchange

In [9]:
# Add qgluc constraints observed in chemostat cultivations
glucose_exchange = model.reactions.get_by_id('Ex_glc_D')
glucose_exchange.bounds = (-0.72, -0.7)
glucose_exchange

In [10]:
# Change the reactions for the synthesis of lipids, proteins and sterols from glycerol to those from glucose

model.reactions.get_by_id('LIPIDS_glyc').bounds = (0,0)
model.reactions.get_by_id('PROTEINS_glyc').bounds = (0,0)
model.reactions.get_by_id('STEROLS_glyc').bounds = (0,0)

# note: these reactions from glucose do not have the glucose specification
model.reactions.get_by_id('LIPIDS').bounds = (0,1000)
model.reactions.get_by_id('PROTEINS').bounds = (0,1000)
model.reactions.get_by_id('STEROLS').bounds = (0,1000)

In [11]:
# ATP maintenance requirement (NGAME = Non-Growth Associated Maintenance Energy) based on previous studies on 
# the growth of X33-ROL on Gluc/MeOH from the group (Eric's Master Thesis)

model.reactions.get_by_id('ATPM').bounds = (1.96, 1000)

In [12]:
rolAA = model.reactions.get_by_id('rolAA')
rolAA.bounds = (0,0)
rolRNA = model.reactions.get_by_id('rolRNA')
rolRNA.bounds = (0,0)
rolDNA = model.reactions.get_by_id('rolDNA')
rolDNA.bounds = (0,0)
pROL = model.reactions.get_by_id('pROL')
pROL.bounds = (0,0)
Rol_transport =  model.reactions.get_by_id('ROLt')
Rol_transport.bounds = (0,0)
ROL_exchange = model.exchanges.get_by_id('Ex_rol')
#ROL_exchange.bounds = (0.0003773,1000)
ROL_exchange.bounds = (0,0) # Inferit de Bradford

pFAB = model.reactions.get_by_id('pFAB')
pFAB.bounds = (0,0)
fabAA = model.reactions.get_by_id('fabAA')
fabAA.bounds = (0,0)
fabt = model.reactions.get_by_id('fabt')
fabt.bounds = (0,0)
fabRNA = model.reactions.get_by_id('fabRNA')
fabRNA.bounds = (0,0)
fabDNA = model.reactions.get_by_id('fabDNA')
FAB_exchange = model.exchanges.get_by_id('Ex_fab')
FAB_exchange.bounds = (0,0)


# Extra reactions that must be closed for simulations to run smoothly:

APAT2r = model.reactions.get_by_id('APAT2r')
APAT2r.bounds = (0,0) # reaction not present in Pichia, it is yet to be removed from the model

MMSAD3 = model.reactions.get_by_id('MMSAD3')
MMSAD3.bounds = (0,0) # The reduction reaction of MSA into Acetil-CoA it is due to an unspecific effect. Reaction
# under evaluation of being kept or not.

In [13]:
# REACTION RATIOS PER GLUCOSA METANOL

ReactionRatio1 = model.problem.Constraint(model.reactions.CSm.flux_expression - model.reactions.ACONTm.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio1)

ReactionRatio2 = model.problem.Constraint(model.reactions.AKGDam.flux_expression - model.reactions.FUMm.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio2)

ReactionRatio8 = model.problem.Constraint(68*model.reactions.AKGDam.flux_expression - 46*model.reactions.CSm.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio8)

ReactionRatio9 = model.problem.Constraint(model.reactions.G6PDH2.flux_expression - model.reactions.GND.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio9)

ReactionRatio10 = model.problem.Constraint(0.8*model.reactions.MDHm.flux_expression - model.reactions.FUMm.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio10)

ReactionRatio12 = model.problem.Constraint(35*model.reactions.PYK.flux_expression - 143*model.reactions.PC.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio12)

ReactionRatio13 = model.problem.Constraint(68*model.reactions.PYK.flux_expression - 143*model.reactions.PYRt2m.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio13)


ReactionRatio14 = model.problem.Constraint(40*model.reactions.GAPD.flux_expression - 145*model.reactions.FBA.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio14)


ReactionRatio16 = model.problem.Constraint(model.reactions.GAPD.flux_expression - model.reactions.PYK.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio16)

ReactionRatio20 = model.problem.Constraint(0.18*model.reactions.FALDtx.flux_expression - 0.82*model.reactions.DAS.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio20)

ReactionRatio21 = model.problem.Constraint(model.reactions.G6PDH2.flux_expression + 0.4*model.reactions.Ex_glc_D.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio21)

In [14]:
pfba_WT = cobra.flux_analysis.pfba(model)

In [15]:
pfba_WT.fluxes['Ex_biomass']

0.08372438750356419

In [16]:
nadph_producing_reactions = []

nadph_c = model.metabolites.get_by_id("nadph_c")

for reaction in model.reactions:
    coefficient = reaction.metabolites.get(nadph_c, 0)

    if coefficient > 0:
        nadph_producing_reactions.append({
            "ID": reaction.id,
            "Name": reaction.name,
            "Reaction": reaction.reaction,
            "NADPH stoichiometry": coefficient
        })

for r in nadph_producing_reactions:
    print(r["ID"], "|", r["Name"], "|", r["NADPH stoichiometry"])

CER4DS16 | Ceramide delta-4 desaturase (C16:0) | 1.0
CER4DS18 | Ceramide delta-4 desaturase (C18:0) | 1.0
CER4DS2d16 | Ceramide delta-4 desaturase (C16OH) | 1.0
CER4DS2d18 | Ceramide delta-4 desaturase (C18OH) | 1.0
CER8DS16 | Ceramide delta-8 desaturase (C16:1) | 1.0
CER8DS18 | Ceramide delta-8 desaturase (C18:1) | 1.0
CER8DS2d16 | Ceramide delta-8 desaturase (C16OH:1) | 1.0
CER8DS2d18 | Ceramide delta-8 desaturase (C18OH:1) | 1.0
ARAB1D2 | D-arabinose 1-dehydrogenase (NADP) | 1.0
ALDD20y | aldehyde dehydrogenase (indole-3-acetaldehyde, NADP) | 1.0
ALDD2y | aldehyde dehydrogenase (acetaldehyde, NADP) | 1.0
ATHRDHr | L-allo-threonine dehydrogenase | 1.0
LSERDHr | L-serine dehydrogenase | 1.0
GLYCDy | Glycerol dehydrogenase (NADP-dependent) | 1.0
APRAUR | 5-amino-6-(5-phosphoribosylamino)uracil reductase | 1.0
FRDO | frdo | 1.0
FTHFDH | formyltetrahydrofolate dehydrogenase | 1.0
BDGLC1R | beta-D-Glucose:NADP+ 1-oxoreductase | 1.0
ICDOXSUC | Isocitrate:NADP+ oxidoreductase | 1.0
G6PDH2 | glucose 6-phosphate dehydrogenase | 1.0
GND | phosphogluconate dehydrogenase | 1.0
HMGCOAR | Hydroxymethylglutaryl CoA reductase | 2.0
ICDHy | isocitrate dehydrogenase (NADP) | 1.0
MTHFD | methylenetetrahydrofolate dehydrogenase (NADP) | 1.0
PPND2 | prephenate dehydrogenase (NADP) | 1.0
SSALy | succinate-semialdehyde dehydrogenase (NADP) | 1.0
SULR | sulfite reductase (NADPH2) | 3.0

In [17]:
increase = 0.20  # 20% increase

nadph_c = model.metabolites.get_by_id("nadph_c")

with model:

    # --------------------------------------------------
    # 1. Identify NADPH-producing reactions
    #    based on the pFBA_WT flux direction
    # --------------------------------------------------

    nadph_producing_reactions = []

    for reaction in model.reactions:

        nadph_stoich = reaction.metabolites.get(nadph_c, 0)
        reference_flux = pfba_WT.fluxes[reaction.id]

        # Net NADPH production in the WT pFBA solution
        if reference_flux * nadph_stoich > 0:

            target_flux = reference_flux * (1 + increase)

            nadph_producing_reactions.append({
                "ID": reaction.id,
                "Name": reaction.name,
                "Reference flux": reference_flux,
                "NADPH stoichiometry": nadph_stoich,
                "Reference NADPH production": (
                    reference_flux * nadph_stoich
                ),
                "Target flux": target_flux
            })

            # Require at least the increased flux
            reaction.lower_bound = target_flux


    # --------------------------------------------------
    # 2. Perform MOMA using pfba_WT as reference
    # --------------------------------------------------

    moma_result = cobra.flux_analysis.moma(
        model,
        solution=pfba_WT,
        linear=False
    )

print("MOMA status:", moma_result.status)

C:\Users\Eric\miniconda3\envs\s2m2\lib\site-packages\cobra\util\solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

MOMA status: infeasible

In [18]:
## Afegir aqui linea de codi per comprovar que la simulació MOMA té un turnover rate més alt que el pfba de ref

In [19]:
# 2. Calculate flux changes

reaction_changes = []

for reaction in model.reactions:

    reaction_id = reaction.id

    reference_flux = pfba_WT.fluxes[reaction_id]
    moma_flux = moma_result.fluxes[reaction_id]

    absolute_change = abs(moma_flux - reference_flux)

    # Proportional change
    if abs(reference_flux) > 1e-12:
        proportional_change = absolute_change / abs(reference_flux)
    else:
        proportional_change = np.nan

    reaction_changes.append({
        "ID": reaction_id,
        "Name": reaction.name,
        "pFBA flux": reference_flux,
        "MOMA flux": moma_flux,
        "Absolute change": absolute_change,
        "Proportional change": proportional_change
    })

In [20]:
flux_threshold = 1e-6

proportional_changes = sorted(
    [
        r for r in reaction_changes
        if abs(r["pFBA flux"]) > flux_threshold
    ],
    key=lambda x: x["Proportional change"],
    reverse=True
)

print("Reactions ordered by proportional flux change:\n")

for r in proportional_changes:
    print(
        r["ID"],
        "|", r["Name"],
        "| pFBA =", r["pFBA flux"],
        "| MOMA =", r["MOMA flux"],
        "| proportional change =", r["Proportional change"]
    )

Reactions ordered by proportional flux change:

MIPCS324_SC | mannose-inositol phosphorylceramide synthase (ceramide-3, 24C), yeast-specific | pFBA = 9.081437404677831e-06 | MOMA = 0.0 | proportional change = 1.0
MIPCS326_SC | mannose-inositol phosphorylceramide synthase (ceramide-3, 26C), yeast-specific | pFBA = 5.93221045982423e-06 | MOMA = 0.0 | proportional change = 1.0
NADH2_u6mh | NADH dehydrogenase, mitochondrial | pFBA = 1.1705697155864612 | MOMA = 0.0 | proportional change = 1.0
GLCCERS18d8 | Glucoceramide synthase (C18OH:2) | pFBA = 1.589023565659411e-06 | MOMA = 0.0 | proportional change = 1.0
GLCCERS18m9 | Glucoceramide synthase (C18OH:2:9m) | pFBA = 4.239628510816851e-06 | MOMA = 0.0 | proportional change = 1.0
CERS118 | Ceramide-1 synthase (18C) | pFBA = 7.699717802560644e-06 | MOMA = 0.0 | proportional change = 1.0
FAcoaRavge | Average fatty acyl-CoA | pFBA = 0.008661781951552327 | MOMA = 0.0 | proportional change = 1.0
STERYLEST | Steryl ester composition (mmol/mmol) | pFBA = 0.00041036671290996956 | MOMA = 0.0 | proportional change = 1.0
DESAT182 | Octadecadienoyl-CoA desaturase (n-C18:2CoA -> n-C18:3CoA) | pFBA = 0.001853621337632198 | MOMA = 0.0 | proportional change = 1.0
CER9MET18 | Ceramide C9 methylase (C18OH:2) | pFBA = 4.239628510816851e-06 | MOMA = 0.0 | proportional change = 1.0
CERavg | Average ceramide | pFBA = 1.6255726139162017e-06 | MOMA = 0.0 | proportional change = 1.0
CERS2d18 | Ceramide-2' synthase (18C) | pFBA = 6.4844157808001355e-06 | MOMA = 0.0 | proportional change = 1.0
GLCCERavg | Average glucoceramide | pFBA = 7.049481237120851e-06 | MOMA = 0.0 | proportional change = 1.0
IPCavg | Average inositol phosphorylceramide | pFBA = 7.775868999638523e-06 | MOMA = 0.0 | proportional change = 1.0
MIP2Cavg | Average mannose-(inositol-P)2-ceramide | pFBA = 7.775868999638523e-06 | MOMA = 0.0 | proportional change = 1.0
MIPCavg | Average mannose-inositol phosphorylceramide | pFBA = 7.775868999638523e-06 | MOMA = 0.0 | proportional change = 1.0
SPHLIPIDS | Sphingolipid composition | pFBA = 3.199946090386224e-05 | MOMA = 0.0 | proportional change = 1.0
CLPNtm | Cardiolipin transport to cytosol for phospholipid composition | pFBA = 9.952816939898197e-06 | MOMA = 0.0 | proportional change = 1.0
NADHter | NADH transport into ER | pFBA = 0.0020862945224463148 | MOMA = 0.0 | proportional change = 1.0
NADter | NAD transport into ER | pFBA = -0.0020862945224463148 | MOMA = 0.0 | proportional change = 1.0
NADPHter | NADPH transport into ER | pFBA = 0.0019321173572375322 | MOMA = 0.0 | proportional change = 1.0
NADPter | NADP transport into ER | pFBA = -0.0019321173572375322 | MOMA = 0.0 | proportional change = 1.0
3C4MOPtm | 3-Carboxy-4-methyl-2-oxopentanoate transport, diffusion, mitochondrial | pFBA = 0.025271369124075814 | MOMA = 0.0 | proportional change = 1.0
AASAD2 | L-aminoadipate-semialdehyde dehydrogenase (NADH) | pFBA = 0.02309704678060825 | MOMA = 0.0 | proportional change = 1.0
ACtp | acetate transport, peroxisomal | pFBA = 0.08741274666116873 | MOMA = 0.0 | proportional change = 1.0
CITtap | citrate/malate antiport into peroxisome | pFBA = 0.08741274666116873 | MOMA = 0.0 | proportional change = 1.0
DDPAm | 2-deoxy-D-arabino-heptulosonate 7-phosphate synthetase, mitochondrial | pFBA = 0.024122837976301922 | MOMA = 0.0 | proportional change = 1.0
DESAT18_2 | Octadecenoyl-CoA desaturase (n-C18:1CoA -> n-C18:2CoA) | pFBA = 0.004200964246502879 | MOMA = 0.0 | proportional change = 1.0
DOLPt2er | dolichol phosphate endoplasmic reticular transport via proton symport | pFBA = -0.02845791931246147 | MOMA = 0.0 | proportional change = 1.0
E4Ptm | D-erythrose 4-phosphate mtiochondrial transport via diffusion | pFBA = 0.024122837976301922 | MOMA = 0.0 | proportional change = 1.0
MALOAAtp | malate/oxaloacetate shuttle | pFBA = 0.08741274666116873 | MOMA = 0.0 | proportional change = 1.0
MANNANter | mannan endoplasmic reticulum transport via diffusion | pFBA = -0.02845791931246147 | MOMA = 0.0 | proportional change = 1.0
MGSA | methylglyoxal synthase | pFBA = 0.00813016058801228 | MOMA = 0.0 | proportional change = 1.0
CERS324 | Ceramide-3 synthase (24C) | pFBA = 1.3506688548303112e-05 | MOMA = 0.0 | proportional change = 1.0
CERS326 | Ceramide-3 synthase (26C) | pFBA = 9.497564282172462e-06 | MOMA = 0.0 | proportional change = 1.0
CYOR_u6m | ubiquinol-6 cytochrome c reductase | pFBA = 4.494101960063031 | MOMA = 0.0 | proportional change = 1.0
IPCS324_PP | Inositol phosphorylceramide synthase (ceramide-3, 24C), yeast-specific | pFBA = 1.2421950726922541e-05 | MOMA = 0.0 | proportional change = 1.0
IPCS326_PP | Inositol phosphorylceramide synthase (ceramide-3, 26C), yeast-specific | pFBA = 8.802283707590808e-06 | MOMA = 0.0 | proportional change = 1.0
MIP2CS324_PP | mannose-(inositol-P)2-ceramide synthase (ceramide-3, 24C), yeast specific | pFBA = 4.572988558687415e-06 | MOMA = 0.0 | proportional change = 1.0
MIP2CS326_PP | mannose-(inositol-P)2-ceramide synthase (ceramide-3, 26C), yeast-specific | pFBA = 3.1196786426549756e-06 | MOMA = 0.0 | proportional change = 1.0
2DDA7Ptm | 2-Dehydro-3-deoxy-D-arabino-heptonate7-phohsphate mitochondrial transport via diffusion | pFBA = -0.024122837976301922 | MOMA = 0.0 | proportional change = 1.0
2OXOADPtim | 2-oxoadipate transport out of mitochondria via diffusion | pFBA = 0.02309704678060825 | MOMA = 0.0 | proportional change = 1.0
ACACT1m | acetyl-CoA C-acetyltransferase, mitochondrial | pFBA = 0.012518269481002906 | MOMA = 0.0 | proportional change = 1.0
ACSm | acetyl-CoA synthetase | pFBA = 0.043888239226530595 | MOMA = 0.0 | proportional change = 1.0
ACSp | acetyl-CoA synthetase | pFBA = 0.08741274666116873 | MOMA = 0.0 | proportional change = 1.0
ADK1 | adenylate kinase | pFBA = 0.29408731781458264 | MOMA = 0.0 | proportional change = 1.0
AKGDam | oxoglutarate dehydrogenase (lipoamide) | pFBA = 0.22432491824603204 | MOMA = 0.0 | proportional change = 1.0
ASPt2m | aspartate mitochondrial transport via proton symport | pFBA = 0.03364508511286307 | MOMA = 0.0 | proportional change = 1.0
ATPtm_H | ADP/ATP transporter, mitochondrial | pFBA = 8.022674467211997 | MOMA = 0.0 | proportional change = 1.0
CITtbm | citrate transport, mitochondrial | pFBA = -0.024122837976301922 | MOMA = 0.0 | proportional change = 1.0
DESAT16 | Palmitoyl-CoA desaturase (n-C16:0CoA -> n-C16:1CoA) | pFBA = 0.0002858388044012268 | MOMA = 0.0 | proportional change = 1.0
D_LACtm | D-lactate transport, mitochondrial | pFBA = 0.010561952324791901 | MOMA = 0.0 | proportional change = 1.0
dolpmmer | Dolichyl-phosphate-mannose--protein mannosyltransferase, endoplasmic reticular | pFBA = 0.02845791931246147 | MOMA = 0.0 | proportional change = 1.0
ERGSTter | Ergosterol transport, ER | pFBA = 0.0019321173572375322 | MOMA = 0.0 | proportional change = 1.0
ERGTETROLter | Ergosta-5,6,22,24,(28)-tetraen-3beta-ol endoplamic reticular transport | pFBA = 0.0019321173572375322 | MOMA = 0.0 | proportional change = 1.0
FBA3 | Sedoheptulose 1,7-bisphosphate D-glyceraldehyde-3-phosphate-lyase | pFBA = 0.005118623090488207 | MOMA = 0.0 | proportional change = 1.0
GK2 | guanylate kinase (GMP:dATP) | pFBA = 5.61288293823895e-05 | MOMA = 0.0 | proportional change = 1.0
GLCt1 | glucose transport (uniport) | pFBA = 0.72 | MOMA = 0.0 | proportional change = 1.0
GLUK | Glucokinase | pFBA = 0.29714285231399484 | MOMA = 0.0 | proportional change = 1.0
H2Oter | H2O endoplasmic reticulum transport | pFBA = -0.0020862945224463148 | MOMA = 0.0 | proportional change = 1.0
HCO3E | HCO3 equilibration reaction | pFBA = 0.3450464839197548 | MOMA = 0.0 | proportional change = 1.0
HICITDm | homoisocitrate dehydrogenase | pFBA = 0.02309704678060825 | MOMA = 0.0 | proportional change = 1.0
HMGCOASm | Hydroxymethylglutaryl CoA synthase, mitochondrial | pFBA = -0.012518269481002906 | MOMA = 0.0 | proportional change = 1.0
ICDHxm | Isocitrate dehydrogenase (NAD+) | pFBA = 0.2798853470127899 | MOMA = 0.0 | proportional change = 1.0
ICDHym | Isocitrate dehydrogenase (NADP+) | pFBA = 0.07666306841038345 | MOMA = 0.0 | proportional change = 1.0
IPPSm | 2-isopropylmalate synthase, mitochondrial | pFBA = 0.025271369124075814 | MOMA = 0.0 | proportional change = 1.0
MEVK2 | mevalonate kinase (ctp) | pFBA = 0.0030218593348001594 | MOMA = 0.0 | proportional change = 1.0
MTHFC | methenyltetrahydrofolate cyclohydrolase | pFBA = -0.050215554801436316 | MOMA = 0.0 | proportional change = 1.0
MTHFCm | methenyltetrahydrifikate cyclohydrolase, mitochondrial | pFBA = 0.014954557619505454 | MOMA = 0.0 | proportional change = 1.0
NADH2_u6cm | NADH dehydrogenase, cytosolic/mitochondrial | pFBA = 3.029122494838624 | MOMA = 0.0 | proportional change = 1.0
O2ter | O2  transport, endoplasmic reticulum | pFBA = 0.0020862945224463148 | MOMA = 0.0 | proportional change = 1.0
OMCDCm | 2-oxo-4-methyl-3-carboxypentanoate decarboxylation | pFBA = 0.025271369124075814 | MOMA = 0.0 | proportional change = 1.0
OXAGm | non-enzymatic reaction | pFBA = 0.02309704678060825 | MOMA = 0.0 | proportional change = 1.0
PAtm_PP | phosphatidate reversible transport, mitochondrial, yeast-specific | pFBA = 1.9905633879796393e-05 | MOMA = 0.0 | proportional change = 1.0
PFK_3 | phosphofructokinase (s7p) | pFBA = 0.005118623090488207 | MOMA = 0.0 | proportional change = 1.0
PIt2m | phosphate transporter, mitochondrial | pFBA = 7.998501530253447 | MOMA = 0.0 | proportional change = 1.0
PPNCL2 | phosphopantothenate-cysteine ligase | pFBA = 8.74550633907234e-06 | MOMA = 0.0 | proportional change = 1.0
PYRt2m | pyruvate mitochondrial transport via proton symport | pFBA = 0.47390974586205376 | MOMA = 0.0 | proportional change = 1.0
RNTR1 | ribonucleoside-triphosphate reductase (ATP) | pFBA = 5.61288293823895e-05 | MOMA = 0.0 | proportional change = 1.0
SLFAT | sulfate adenylyltransferase (ADP) | pFBA = 0.003331933895130461 | MOMA = 0.0 | proportional change = 1.0
SQ23EPXter | Squalene-2,3-epoxide endoplamic reticular transport | pFBA = 0.0020862945224463148 | MOMA = 0.0 | proportional change = 1.0
SQLter | squalene endoplamic reticular transport | pFBA = 0.0020862945224463148 | MOMA = 0.0 | proportional change = 1.0
SUCD2_u6m | succinate dehydrogenase (ubiquinone-6), mitochondrial | pFBA = 0.2867993284004532 | MOMA = 0.0 | proportional change = 1.0
DASYNm_PP | CDP-Diacylglycerol synthetase, yeast-specific, mitochondrial | pFBA = 1.9905633879796393e-05 | MOMA = 0.0 | proportional change = 1.0
G6PI3 | Glucose-6-phosphate isomerase | pFBA = 0.29714285231399484 | MOMA = 0.0 | proportional change = 1.0
C3STDH2 | C-3 sterol dehydrogenase (zymosterol) | pFBA = 0.002076071679286328 | MOMA = 0.0 | proportional change = 1.0
C3STKR2 | C-3 sterol keto reductase (zymosterol) | pFBA = 0.002076071679286328 | MOMA = 0.0 | proportional change = 1.0
C4STMO2 | C-4 sterol methyl oxidase (4-methylzymosterol) | pFBA = 0.002076071679286328 | MOMA = 0.0 | proportional change = 1.0
DHORD4i | dihydoorotic acid (ubiquinone-6), irreversible | pFBA = 0.007610337513105227 | MOMA = 0.0 | proportional change = 1.0
C22STDSx | C-22 sterol desaturase (NAD) | pFBA = 0.0019321173572375322 | MOMA = 0.0 | proportional change = 1.0
LNS14DMx | cytochrome P450 lanosterol 14-alpha-demethylase (NAD) | pFBA = 0.002076071679286328 | MOMA = 0.0 | proportional change = 1.0
CTPtm | CTP/CMP antiport | pFBA = 1.9905633879796393e-05 | MOMA = 0.0 | proportional change = 1.0
D_LACt2m | D-lactate/pyruvate antiport, mitochondrial | pFBA = -0.010561952324791901 | MOMA = 0.0 | proportional change = 1.0
GLUt7m | Glutamate transport (uniporter), mitochondrial | pFBA = 0.039256250818115374 | MOMA = 0.0 | proportional change = 1.0
TRDOXtp | oxidized thioredoxin peroxisomal transport via diffusion | pFBA = 0.0036040214096388847 | MOMA = 0.0 | proportional change = 1.0
TRDRDtp | reduced thioredoxin peroxisomal transport via diffusion | pFBA = -0.0036040214096388847 | MOMA = 0.0 | proportional change = 1.0
THIORDXp | hydrogen peroxide reductase (thioredoxin), peroxisomal | pFBA = -0.0036040214096388847 | MOMA = 0.0 | proportional change = 1.0
10FTHFtm | 10-Formyltetrahydrofolate mitochondrial transport via diffusion | pFBA = -0.014954557619505454 | MOMA = 0.0 | proportional change = 1.0
AHSERL2 | O-acetylhomoserine (thiol)-lyase | pFBA = 0.002789696591618759 | MOMA = 0.0 | proportional change = 1.0
ASP1DC | aspartate 1-decarboxylase | pFBA = 8.74550633907234e-06 | MOMA = 0.0 | proportional change = 1.0
FALDH2 | formaldehyde dehydrogenase | pFBA = 1.0168 | MOMA = 0.0 | proportional change = 1.0
FALGTHLs | formaldehyde glutathione ligase (spontaneous) | pFBA = 1.0168 | MOMA = 0.0 | proportional change = 1.0
GLYtm | glycine passive transport to mitochondria | pFBA = -0.014953887824405432 | MOMA = 0.0 | proportional change = 1.0
HSERTAm | homoserine O-trans-acetylase | pFBA = 0.002789780316006262 | MOMA = 0.0 | proportional change = 1.0
MAN1PT2 | mannose-1-phosphate guanylyltransferase (GDP) | pFBA = 0.028473471050460747 | MOMA = 0.0 | proportional change = 1.0
MI3PP | myo-inositol 3-phosphatase | pFBA = 7.56026647805627e-05 | MOMA = 0.0 | proportional change = 1.0
P5CRm | pyrroline-5-carboxylate reductase (m) | pFBA = 0.013579258409203076 | MOMA = 0.0 | proportional change = 1.0
PDHa1 | pyruvate dehydrogenase (lipoamide) | pFBA = 0.3923121697509949 | MOMA = 0.0 | proportional change = 1.0
PDHa2 | pyruvate dehydrogenase (lipoamide) | pFBA = 0.37643551414869403 | MOMA = 0.0 | proportional change = 1.0
PPItx | Diphosphate transporter, peroxisome | pFBA = 0.08741274666116873 | MOMA = 0.0 | proportional change = 1.0
PUTA3 | puta3 | pFBA = -0.013579258409203076 | MOMA = 0.0 | proportional change = 1.0
THFtm | 5,6,7,8-Tetrahydrofolate transport, diffusion, mitochondrial | pFBA = 0.014954557619505454 | MOMA = 0.0 | proportional change = 1.0
FCYTB5R | NADH:ferricytochrome-b5 oxidoreductase | pFBA = 0.006825484177823233 | MOMA = 0.0 | proportional change = 1.0
CYSTH2SS | L-serine hydro-lyase (adding hydrogen sulfide, L-cysteine-forming) | pFBA = 0.000542237303511702 | MOMA = 0.0 | proportional change = 1.0
E3MMALOR | (2R,3S)-3-methylmalate:NAD+ oxidoreductase | pFBA = 0.015876655602300876 | MOMA = 0.0 | proportional change = 1.0
HISTD | histidinol dehydrogenase (step 2) | pFBA = 0.006646041880032925 | MOMA = 0.0 | proportional change = 1.0
FCYTDESAT18 | steroyl-CoA,hydrogen-donor:oxygen oxidoreductase | pFBA = 0.006825484177823233 | MOMA = 0.0 | proportional change = 1.0
PDHbrm | pyruvate dehydrogenase (dihydrolipoamide) reversible | pFBA = 0.37643551414869403 | MOMA = 0.0 | proportional change = 1.0
HISTD1 | histidinol dehydrogenase (step 1) | pFBA = 0.006646041880032925 | MOMA = 0.0 | proportional change = 1.0
CITCONH | (R)-2-Methylmalate hydro-lyase | pFBA = 0.015876655602300876 | MOMA = 0.0 | proportional change = 1.0
E3MMALH | 3-isopropylmalate/(R)-2-methylmalate dehydratase | pFBA = 0.015876655602300876 | MOMA = 0.0 | proportional change = 1.0
ALACPYRL | (S)-2-Aceto-2-hydroxybutanoate pyruvate-lyase (carboxylating) | pFBA = 0.015876655602300876 | MOMA = 0.0 | proportional change = 1.0
3H3M2OPR | (R)-2,3-Dihydroxy-3-methylpentanoate:NADP+ oxidoreductase | pFBA = 0.015876655602300876 | MOMA = 0.0 | proportional change = 1.0
3H3M2OPS | (R)-2,3-Dihydroxy-3-methylpentanoate:NADP+ oxidoreductase | pFBA = 0.015876655602300876 | MOMA = 0.0 | proportional change = 1.0
MI3PS | 1D-myo-inositol-3-phosphate lyase (isomerizing) | pFBA = 7.56026647805627e-05 | MOMA = 0.0 | proportional change = 1.0
CITMALS | D-citramalate synthase | pFBA = 0.015876655602300876 | MOMA = 0.0 | proportional change = 1.0
STEROLS | Sterol composition (mmol/mmol) | pFBA = 0.0016759278095363453 | MOMA = 0.0 | proportional change = 1.0
GLYCERIDES | Diglycerides and triglycerides composition (mmol/mmol) | pFBA = 0.002557143732888859 | MOMA = 0.0 | proportional change = 1.0
LIPIDS | Lipid composition (mmol/g) | pFBA = 0.003516424275149696 | MOMA = 0.0 | proportional change = 1.0
growth | Growth | pFBA = 0.08372438750356419 | MOMA = 0.0 | proportional change = 1.0
ACHMStm | O-acetyl-L-homoserine mitochondrial permease | pFBA = -0.002789780316006262 | MOMA = 0.0 | proportional change = 1.0
HOMtm | L-homoserine mitochondrial permease | pFBA = -0.0027897803160062615 | MOMA = 0.0 | proportional change = 1.0
1PYR5Ctm | 1-Pyrroline-5-carboxylate transport into mitochondria | pFBA = 0.013579258409203076 | MOMA = 0.0 | proportional change = 1.0
4MOPtm | 4-Methyl-2-oxopentanoate transport into mitochondria | pFBA = -0.025271369124075814 | MOMA = 0.0 | proportional change = 1.0
AKGMALtm | alpha-ketoglutarate/malate transporter | pFBA = 0.1051424040445575 | MOMA = 0.0 | proportional change = 1.0
SERtm | L-Serine mitochondrial permease | pFBA = 0.014954557619505454 | MOMA = 0.0 | proportional change = 1.0
G5SADsm | L-glutamate 5-semialdehyde dehydratase (spontaneous) | pFBA = 0.013579258409203076 | MOMA = 0.0 | proportional change = 1.0
PHOSPHOLIPIDS | Phospholipid composition (mmol/mmol) | pFBA = 0.0007212186188332027 | MOMA = 0.0 | proportional change = 1.0
PROTEINS | Aminoacid composition mmol/g) | pFBA = 0.04102494987674645 | MOMA = 0.0 | proportional change = 1.0
CARBOHYDRATES | Carbohydrate composition (mmol/g) | pFBA = 0.027629047876176184 | MOMA = 0.0 | proportional change = 1.0
RNA | RNA composition (mmol/g) - polymerization | pFBA = 0.0048560144752067234 | MOMA = 0.0 | proportional change = 1.0
DNA | DNA composition (mmol/g) - polymerization | pFBA = 8.372438750356419e-05 | MOMA = 0.0 | proportional change = 1.0
COF | Cofactor composition (mmol/g DCW) | pFBA = 0.08372438750356419 | MOMA = 0.0 | proportional change = 1.0
CERS224 | Ceramide-2 synthase (24C) | pFBA = 1.3726041524855154e-05 | MOMA = 0.0 | proportional change = 1.0
CERS226 | Ceramide-2 synthase (26C) | pFBA = 9.634784498418248e-06 | MOMA = 0.0 | proportional change = 1.0
LGTHL | lactoylglutathione lyase | pFBA = 0.00813016058801228 | MOMA = 0.0 | proportional change = 1.0
METOHte | Methanol extracellular transport | pFBA = -1.24 | MOMA = 0.0 | proportional change = 1.0
METOHtx | Methanol peroxisomal transport | pFBA = 1.24 | MOMA = 0.0 | proportional change = 1.0
O2tx | oxygen peroxisomal transport | pFBA = -0.6181979892951805 | MOMA = 0.0 | proportional change = 1.0
CDPDGPm_PP | CDP-diacylglycerol--serine O-phosphatidyltransferae, yeast-specific, mitochondrial | pFBA = 9.952816939898197e-06 | MOMA = 0.0 | proportional change = 1.0
13GS | 1,3-beta-glucan synthase | pFBA = 0.08468303174048 | MOMA = 0.0 | proportional change = 1.0
3C3HMPtm | 2-Isopropylmalate transport, diffusion, mitochondrial | pFBA = -0.025271369124075814 | MOMA = 0.0 | proportional change = 1.0
3DSPHR | 3-Dehydrosphinganine reductase | pFBA = 3.2002660849952624e-05 | MOMA = 0.0 | proportional change = 1.0
3MOBtm | 3-methyl-2-oxobutanoate transport, diffusion, mitochondrial | pFBA = -0.020808395093849522 | MOMA = 0.0 | proportional change = 1.0
3MOPtm | 3-Methyl-2-oxopentanoate transport, diffusion, mitochondrial | pFBA = -0.015876655602300876 | MOMA = 0.0 | proportional change = 1.0
AATA | 2-aminoadipate transaminase | pFBA = 0.02309704678060825 | MOMA = 0.0 | proportional change = 1.0
ACCOACr | acetyl-CoA carboxylase, reversible reaction | pFBA = 0.06852781803212452 | MOMA = 0.0 | proportional change = 1.0
ACGAM6PS | N-acetylglucosamine-6-phosphate synthase | pFBA = 0.005663954814616117 | MOMA = 0.0 | proportional change = 1.0
ACGAMPM | phosphoacetylglucosamine mutase | pFBA = 0.005663954814616117 | MOMA = 0.0 | proportional change = 1.0
ACGKm | acetylglutamate kinase, mitochondrial | pFBA = 0.029661038760887687 | MOMA = 0.0 | proportional change = 1.0
ACLSm | acetolactate synthase, mitochondrial | pFBA = 0.04607976421792534 | MOMA = 0.0 | proportional change = 1.0
ACOATA | Acetyl-CoA ACP transacylase | pFBA = 0.008734449055203784 | MOMA = 0.0 | proportional change = 1.0
ACONT | aconitase | pFBA = 0.08741274666116888 | MOMA = 0.0 | proportional change = 1.0
ACONTm | Aconitate hydratase | pFBA = 0.3316107487115256 | MOMA = 0.0 | proportional change = 1.0

In [21]:
absolute_changes = sorted(
    reaction_changes,
    key=lambda x: x["Absolute change"],
    reverse=True
)

print("Reactions ordered by absolute flux change:\n")

for r in absolute_changes:
    print(
        r["ID"],
        "|", r["Name"],
        "| pFBA =", r["pFBA flux"],
        "| MOMA =", r["MOMA flux"],
        "| absolute change =", r["Absolute change"]
    )

Reactions ordered by absolute flux change:

H2Otm | H2O transport, mitochondrial | pFBA = -11.822271840165344 | MOMA = 0.0 | absolute change = 11.822271840165344
ATPtm_H | ADP/ATP transporter, mitochondrial | pFBA = 8.022674467211997 | MOMA = 0.0 | absolute change = 8.022674467211997
PIt2m | phosphate transporter, mitochondrial | pFBA = 7.998501530253447 | MOMA = 0.0 | absolute change = 7.998501530253447
ATPS3m | ATP synthase, mitochondrial | pFBA = 7.915787735975014 | MOMA = 0.0 | absolute change = 7.915787735975014
H2Ot | H2O transport via diffusion | pFBA = -4.780590560868632 | MOMA = 0.0 | absolute change = 4.780590560868632
Ex_h2o | H2O exchange | pFBA = 4.780590560868632 | MOMA = 0.0 | absolute change = 4.780590560868632
CYOR_u6m | ubiquinol-6 cytochrome c reductase | pFBA = 4.494101960063031 | MOMA = 0.0 | absolute change = 4.494101960063031
NADH2_u6cm | NADH dehydrogenase, cytosolic/mitochondrial | pFBA = 3.029122494838624 | MOMA = 0.0 | absolute change = 3.029122494838624
O2t | o2 transport (diffusion) | pFBA = 2.9071705013967044 | MOMA = 0.0 | absolute change = 2.9071705013967044
Ex_o2 | Oxygen exchange | pFBA = -2.9071705013967044 | MOMA = 0.0 | absolute change = 2.9071705013967044
CO2t | CO2 transporter via diffusion | pFBA = -2.3730677913920046 | MOMA = 0.0 | absolute change = 2.3730677913920046
Ex_co2 | CO2 exchange | pFBA = 2.3730677913920046 | MOMA = 0.0 | absolute change = 2.3730677913920046
O2tm | O2 transport (diffusion) | pFBA = 2.2511163952230717 | MOMA = 0.0 | absolute change = 2.2511163952230717
CYOOm | cytochrome c oxidase, mitochondrial | pFBA = 2.251116060325522 | MOMA = 0.0 | absolute change = 2.251116060325522
METOHte | Methanol extracellular transport | pFBA = -1.24 | MOMA = 0.0 | absolute change = 1.24
METOHtx | Methanol peroxisomal transport | pFBA = 1.24 | MOMA = 0.0 | absolute change = 1.24
AOD | Alcohol oxidase | pFBA = 1.24 | MOMA = 0.0 | absolute change = 1.24
NADH2_u6mh | NADH dehydrogenase, mitochondrial | pFBA = 1.1705697155864612 | MOMA = 0.0 | absolute change = 1.1705697155864612
H2Otp | H2O transport, peroxisomal | pFBA = -1.1489832319291924 | MOMA = 0.0 | absolute change = 1.1489832319291924
CO2tm | CO2 transport (diffusion), mitochondrial | pFBA = -1.0682368709746086 | MOMA = 0.0 | absolute change = 1.0682368709746086
FALDH2 | formaldehyde dehydrogenase | pFBA = 1.0168 | MOMA = 0.0 | absolute change = 1.0168
FALGTHLs | formaldehyde glutathione ligase (spontaneous) | pFBA = 1.0168 | MOMA = 0.0 | absolute change = 1.0168
SFGTH | S-Formylglutathione hydralase | pFBA = 1.0168 | MOMA = 0.0 | absolute change = 1.0168
FALDtx | formaldehyde peroxisomal transport | pFBA = 1.0168 | MOMA = 0.0 | absolute change = 1.0168
ENO | enolase | pFBA = 0.9966043185040248 | MOMA = 0.0 | absolute change = 0.9966043185040248
GAPD | glyceraldehyde-3-phosphate dehydrogenase | pFBA = 0.9966043185040248 | MOMA = 0.0 | absolute change = 0.9966043185040248
PGK | phosphoglycerate kinase | pFBA = -0.9966043185040248 | MOMA = 0.0 | absolute change = 0.9966043185040248
PGM | phosphoglycerate mutase | pFBA = -0.9966043185040248 | MOMA = 0.0 | absolute change = 0.9966043185040248
PYK | pyruvate kinase | pFBA = 0.9966043185040248 | MOMA = 0.0 | absolute change = 0.9966043185040248
FDH | formate dehydrogenase | pFBA = 0.9612962365380372 | MOMA = 0.0 | absolute change = 0.9612962365380372
GLCt1 | glucose transport (uniport) | pFBA = 0.72 | MOMA = 0.0 | absolute change = 0.72
Ht | H+ diffusion | pFBA = -0.6675096384597891 | MOMA = 0.0 | absolute change = 0.6675096384597891
Ex_h | H+ exchange | pFBA = 0.6512827067581404 | MOMA = 0.0 | absolute change = 0.6512827067581404
CATp | catalase | pFBA = 0.6218020107048194 | MOMA = 0.0 | absolute change = 0.6218020107048194
O2tx | oxygen peroxisomal transport | pFBA = -0.6181979892951805 | MOMA = 0.0 | absolute change = 0.6181979892951805
NH4t | ammonia reversible transport | pFBA = 0.6024766391006862 | MOMA = 0.0 | absolute change = 0.6024766391006862
Ex_nh4 | Ammonium exchange | pFBA = -0.6024766391006862 | MOMA = 0.0 | absolute change = 0.6024766391006862
PDHcm | pyruvate dehydrogenase (dihydrolipoamide dehydrogenase) | pFBA = 0.6007604323947261 | MOMA = 0.0 | absolute change = 0.6007604323947261
TPI | triose-phosphate isomerase | pFBA = 0.4918154284324514 | MOMA = 0.0 | absolute change = 0.4918154284324514
GLUDyi | glutamate dehydrogenase (NADP) | pFBA = 0.48060201106694916 | MOMA = 0.0 | absolute change = 0.48060201106694916
PYRt2m | pyruvate mitochondrial transport via proton symport | pFBA = 0.47390974586205376 | MOMA = 0.0 | absolute change = 0.47390974586205376
PPA | inorganic diphosphatase | pFBA = 0.4437646162151111 | MOMA = 0.0 | absolute change = 0.4437646162151111
HEX1 | hexokinase (D-glucose:ATP) | pFBA = 0.42285714768600513 | MOMA = 0.0 | absolute change = 0.42285714768600513
PDHa1 | pyruvate dehydrogenase (lipoamide) | pFBA = 0.3923121697509949 | MOMA = 0.0 | absolute change = 0.3923121697509949
PDHa2 | pyruvate dehydrogenase (lipoamide) | pFBA = 0.37643551414869403 | MOMA = 0.0 | absolute change = 0.37643551414869403
PDHbrm | pyruvate dehydrogenase (dihydrolipoamide) reversible | pFBA = 0.37643551414869403 | MOMA = 0.0 | absolute change = 0.37643551414869403
HCO3E | HCO3 equilibration reaction | pFBA = 0.3450464839197548 | MOMA = 0.0 | absolute change = 0.3450464839197548
ACONTm | Aconitate hydratase | pFBA = 0.3316107487115256 | MOMA = 0.0 | absolute change = 0.3316107487115256
CSm | citrate synthase | pFBA = 0.3316107487115256 | MOMA = 0.0 | absolute change = 0.3316107487115256
GLUK | Glucokinase | pFBA = 0.29714285231399484 | MOMA = 0.0 | absolute change = 0.29714285231399484
G6PI3 | Glucose-6-phosphate isomerase | pFBA = 0.29714285231399484 | MOMA = 0.0 | absolute change = 0.29714285231399484
ADK1 | adenylate kinase | pFBA = 0.29408731781458264 | MOMA = 0.0 | absolute change = 0.29408731781458264
PGL | 6-phosphogluconolactonase | pFBA = 0.288 | MOMA = 0.0 | absolute change = 0.288
SUCD2_u6m | succinate dehydrogenase (ubiquinone-6), mitochondrial | pFBA = 0.2867993284004532 | MOMA = 0.0 | absolute change = 0.2867993284004532
MDHm | malate dehydrogenase, mitochondrial | pFBA = 0.28040614780754003 | MOMA = 0.0 | absolute change = 0.28040614780754003
ICDHxm | Isocitrate dehydrogenase (NAD+) | pFBA = 0.2798853470127899 | MOMA = 0.0 | absolute change = 0.2798853470127899
FBA | fructose-bisphosphate aldolase | pFBA = 0.2749253292424896 | MOMA = 0.0 | absolute change = 0.2749253292424896
PFK | phosphofructokinase | pFBA = 0.2749253292424896 | MOMA = 0.0 | absolute change = 0.2749253292424896
PC | pyruvate carboxylase | pFBA = 0.24392413389958645 | MOMA = 0.0 | absolute change = 0.24392413389958645
RPE | ribulose 5-phosphate 3-epimerase | pFBA = 0.24023860960844728 | MOMA = 0.0 | absolute change = 0.24023860960844728
PYRDC | pyruvate decarboxylase | pFBA = 0.22731408307605525 | MOMA = 0.0 | absolute change = 0.22731408307605525
AKGDam | oxoglutarate dehydrogenase (lipoamide) | pFBA = 0.22432491824603204 | MOMA = 0.0 | absolute change = 0.22432491824603204
AKGDbm | oxoglutarate dehydrogenase (dihydrolipoamide S-succinyltransferase) | pFBA = 0.22432491824603204 | MOMA = 0.0 | absolute change = 0.22432491824603204
FUMm | fumarase, mitochondrial | pFBA = 0.22432491824603204 | MOMA = 0.0 | absolute change = 0.22432491824603204
SUCOASm | Succinate--CoA ligase (ADP-forming) | pFBA = -0.22432424845093202 | MOMA = 0.0 | absolute change = 0.22432424845093202
DHAK | Dihydroxyacetone kinase | pFBA = 0.22319999999999998 | MOMA = 0.0 | absolute change = 0.22319999999999998
DAS | Dihydroxyacetone synthase | pFBA = 0.22319999999999998 | MOMA = 0.0 | absolute change = 0.22319999999999998
DHAtx | Dihydroxyacetone peroxisomal transport | pFBA = 0.22319999999999998 | MOMA = 0.0 | absolute change = 0.22319999999999998
G3Ptx | Glyceraldehyde 3-phosphate peroxisomal transport | pFBA = 0.22319999999999998 | MOMA = 0.0 | absolute change = 0.22319999999999998
XU5Ptx | xylulose-5-phosphate transport | pFBA = 0.22319999999999998 | MOMA = 0.0 | absolute change = 0.22319999999999998
NDPK2 | nucleoside-diphosphate kinase (ATP:UDP) | pFBA = 0.1436127264355905 | MOMA = 0.0 | absolute change = 0.1436127264355905
ASPTA | aspartate transaminase | pFBA = -0.14092571984113755 | MOMA = 0.0 | absolute change = 0.14092571984113755
GALU | UTP-glucose-1-phosphate uridylyltransferase | pFBA = 0.13417370596794867 | MOMA = 0.0 | absolute change = 0.13417370596794867
PGMT | phosphoglucomutase | pFBA = -0.13417370596794867 | MOMA = 0.0 | absolute change = 0.13417370596794867
GLNS | glutamine synthetase | pFBA = 0.11804410334642966 | MOMA = 0.0 | absolute change = 0.11804410334642966
FUM | fumarase | pFBA = 0.10630075390783755 | MOMA = 0.0 | absolute change = 0.10630075390783755
AKGMALtm | alpha-ketoglutarate/malate transporter | pFBA = 0.1051424040445575 | MOMA = 0.0 | absolute change = 0.1051424040445575
ALATA_L | L-alanine transaminase | pFBA = -0.10071050068330702 | MOMA = 0.0 | absolute change = 0.10071050068330702
ACS | acetyl-CoA synthetase | pFBA = 0.09880287750436217 | MOMA = 0.0 | absolute change = 0.09880287750436217
ACONT | aconitase | pFBA = 0.08741274666116888 | MOMA = 0.0 | absolute change = 0.08741274666116888
ACtp | acetate transport, peroxisomal | pFBA = 0.08741274666116873 | MOMA = 0.0 | absolute change = 0.08741274666116873
CITtap | citrate/malate antiport into peroxisome | pFBA = 0.08741274666116873 | MOMA = 0.0 | absolute change = 0.08741274666116873
MALOAAtp | malate/oxaloacetate shuttle | pFBA = 0.08741274666116873 | MOMA = 0.0 | absolute change = 0.08741274666116873
ACSp | acetyl-CoA synthetase | pFBA = 0.08741274666116873 | MOMA = 0.0 | absolute change = 0.08741274666116873
PPItx | Diphosphate transporter, peroxisome | pFBA = 0.08741274666116873 | MOMA = 0.0 | absolute change = 0.08741274666116873
ATP2tp_H | AMP/ATP transporter, peroxisomal | pFBA = 0.08741274666116873 | MOMA = 0.0 | absolute change = 0.08741274666116873
CSp | citrate synthase | pFBA = 0.08741274666116873 | MOMA = 0.0 | absolute change = 0.08741274666116873
13GS | 1,3-beta-glucan synthase | pFBA = 0.08468303174048 | MOMA = 0.0 | absolute change = 0.08468303174048
growth | Growth | pFBA = 0.08372438750356419 | MOMA = 0.0 | absolute change = 0.08372438750356419
COF | Cofactor composition (mmol/g DCW) | pFBA = 0.08372438750356419 | MOMA = 0.0 | absolute change = 0.08372438750356419
Ex_biomass | Biomass exchange | pFBA = 0.08372438750356419 | MOMA = 0.0 | absolute change = 0.08372438750356419
biomass_glc_meoh_60/40 | Biomass composition (g/g) - 60/40 Glucose/Methanol | pFBA = 0.08372438750356419 | MOMA = 0.0 | absolute change = 0.08372438750356419
ICDHym | Isocitrate dehydrogenase (NADP+) | pFBA = 0.07666306841038345 | MOMA = 0.0 | absolute change = 0.07666306841038345
ACCOACr | acetyl-CoA carboxylase, reversible reaction | pFBA = 0.06852781803212452 | MOMA = 0.0 | absolute change = 0.06852781803212452
AGTi | Alanine glyoxylate aminotransferase (irreversible) | pFBA = 0.06247524739817932 | MOMA = 0.0 | absolute change = 0.06247524739817932
ICL | Isocitrate lyase | pFBA = 0.06247507994952118 | MOMA = 0.0 | absolute change = 0.06247507994952118
SUCFUMtm | succinate-fumarate transport, mitochondrial | pFBA = 0.06247441015442115 | MOMA = 0.0 | absolute change = 0.06247441015442115
Ex_meoh | Methanol exchange | pFBA = -1.24 | MOMA = -1.18 | absolute change = 0.06000000000000005
G6PDH2 | glucose 6-phosphate dehydrogenase | pFBA = 0.288 | MOMA = 0.34559999999999996 | absolute change = 0.057599999999999985
GND | phosphogluconate dehydrogenase | pFBA = 0.288 | MOMA = 0.34559999999999996 | absolute change = 0.057599999999999985
FTHFLi | formate-tetrahydrofolate ligase | pFBA = 0.057580421211961705 | MOMA = 0.0 | absolute change = 0.057580421211961705
MDH | malate dehydrogenase | pFBA = 0.050219524346445166 | MOMA = 0.0 | absolute change = 0.050219524346445166
MTHFC | methenyltetrahydrofolate cyclohydrolase | pFBA = -0.050215554801436316 | MOMA = 0.0 | absolute change = 0.050215554801436316
MTHFD | methylenetetrahydrofolate dehydrogenase (NADP) | pFBA = -0.050215554801436316 | MOMA = 0.0 | absolute change = 0.050215554801436316
CITtam | citrate transport, mitochondrial | pFBA = 0.04906050468794948 | MOMA = 0.0 | absolute change = 0.04906050468794948
GLCS2 | glycogen synthase (UDPGlc) | pFBA = 0.04887578569295567 | MOMA = 0.0 | absolute change = 0.04887578569295567
PPCK | phosphoenolpyruvate carboxykinase | pFBA = 0.048245675952603845 | MOMA = 0.0 | absolute change = 0.048245675952603845
RPI | ribose-5-phosphate isomerase | pFBA = -0.047761055494002655 | MOMA = 0.0 | absolute change = 0.047761055494002655
ACLSm | acetolactate synthase, mitochondrial | pFBA = 0.04607976421792534 | MOMA = 0.0 | absolute change = 0.04607976421792534
DHAD1m | dihydroxy-acid dehydratase (2,3-dihydroxy-3-methylbutanoate), mitochondrial | pFBA = 0.04607976421792534 | MOMA = 0.0 | absolute change = 0.04607976421792534
KARA1im | acetohydroxy acid isomeroreductase, mitochondrial | pFBA = 0.04607976421792534 | MOMA = 0.0 | absolute change = 0.04607976421792534
ALDD2y | aldehyde dehydrogenase (acetaldehyde, NADP) | pFBA = 0.22731408307605525 | MOMA = 0.2727768996912663 | absolute change = 0.04546281661521104
GHMT2r | glycine hydroxymethyltransferase, reversible | pFBA = -0.0442388158127878 | MOMA = 0.0 | absolute change = 0.0442388158127878
PPAm | inorganic diphosphatase | pFBA = 0.0439083123091854 | MOMA = 0.0 | absolute change = 0.0439083123091854
ACSm | acetyl-CoA synthetase | pFBA = 0.043888239226530595 | MOMA = 0.0 | absolute change = 0.043888239226530595
ACtm | acetate transport, mitochondrial | pFBA = 0.043888239226530595 | MOMA = 0.0 | absolute change = 0.043888239226530595
ADK1m | adenylate kinase, mitochondrial | pFBA = 0.043888239226530595 | MOMA = 0.0 | absolute change = 0.043888239226530595
MCOATA | Malonyl-CoA-ACP transacylase | pFBA = 0.04367224527601892 | MOMA = 0.0 | absolute change = 0.04367224527601892
PROTEINS | Aminoacid composition mmol/g) | pFBA = 0.04102494987674645 | MOMA = 0.0 | absolute change = 0.04102494987674645
GLUt7m | Glutamate transport (uniporter), mitochondrial | pFBA = 0.039256250818115374 | MOMA = 0.0 | absolute change = 0.039256250818115374
ASPt2m | aspartate mitochondrial transport via proton symport | pFBA = 0.03364508511286307 | MOMA = 0.0 | absolute change = 0.03364508511286307
ASPTAm | aspartate transaminase | pFBA = 0.03364508511286307 | MOMA = 0.0 | absolute change = 0.03364508511286307
CBPS | carbamoyl-phosphate synthase (glutamine-hydrolysing) | pFBA = 0.032594531988043816 | MOMA = 0.0 | absolute change = 0.032594531988043816
ACGKm | acetylglutamate kinase, mitochondrial | pFBA = 0.029661038760887687 | MOMA = 0.0 | absolute change = 0.029661038760887687
ACOTAim | acteylornithine transaminase, irreversible, mitochondrial | pFBA = 0.029661038760887687 | MOMA = 0.0 | absolute change = 0.029661038760887687
AGPRim | N-acetyl-g-glutamyl-phosphate reductase, irreversible, mitochondrial | pFBA = 0.029661038760887687 | MOMA = 0.0 | absolute change = 0.029661038760887687
ORNt3m | ornithine mitochondrial transport via proton antiport | pFBA = 0.029661038760887687 | MOMA = 0.0 | absolute change = 0.029661038760887687
ORNTACim | ornithine transacetylase, irreversible, mitochondrial | pFBA = 0.029661038760887687 | MOMA = 0.0 | absolute change = 0.029661038760887687
MAN1PT2 | mannose-1-phosphate guanylyltransferase (GDP) | pFBA = 0.028473471050460747 | MOMA = 0.0 | absolute change = 0.028473471050460747
MAN6PI | mannose-6-phosphate isomerase | pFBA = -0.028473471050460747 | MOMA = 0.0 | absolute change = 0.028473471050460747
PMANM | phosphomannomutase | pFBA = -0.028473471050460747 | MOMA = 0.0 | absolute change = 0.028473471050460747
DOLPt2er | dolichol phosphate endoplasmic reticular transport via proton symport | pFBA = -0.02845791931246147 | MOMA = 0.0 | absolute change = 0.02845791931246147
MANNANter | mannan endoplasmic reticulum transport via diffusion | pFBA = -0.02845791931246147 | MOMA = 0.0 | absolute change = 0.02845791931246147
dolpmmer | Dolichyl-phosphate-mannose--protein mannosyltransferase, endoplasmic reticular | pFBA = 0.02845791931246147 | MOMA = 0.0 | absolute change = 0.02845791931246147
DOLPMTcer | Dolichyl-phosphate D-mannosyltransferase | pFBA = 0.02845791931246147 | MOMA = 0.0 | absolute change = 0.02845791931246147
CARBOHYDRATES | Carbohydrate composition (mmol/g) | pFBA = 0.027629047876176184 | MOMA = 0.0 | absolute change = 0.027629047876176184
PRPPS | phosphoribosylpyrophosphate synthetase | pFBA = 0.027180373563821768 | MOMA = 0.0 | absolute change = 0.027180373563821768
3C4MOPtm | 3-Carboxy-4-methyl-2-oxopentanoate transport, diffusion, mitochondrial | pFBA = 0.025271369124075814 | MOMA = 0.0 | absolute change = 0.025271369124075814
IPPSm | 2-isopropylmalate synthase, mitochondrial | pFBA = 0.025271369124075814 | MOMA = 0.0 | absolute change = 0.025271369124075814
OMCDCm | 2-oxo-4-methyl-3-carboxypentanoate decarboxylation | pFBA = 0.025271369124075814 | MOMA = 0.0 | absolute change = 0.025271369124075814
4MOPtm | 4-Methyl-2-oxopentanoate transport into mitochondria | pFBA = -0.025271369124075814 | MOMA = 0.0 | absolute change = 0.025271369124075814
3C3HMPtm | 2-Isopropylmalate transport, diffusion, mitochondrial | pFBA = -0.025271369124075814 | MOMA = 0.0 | absolute change = 0.025271369124075814
IPMD | 3-isopropylmalate dehydrogenase | pFBA = 0.025271369124075814 | MOMA = 0.0 | absolute change = 0.025271369124075814
IPPMIa | 3-isopropylmalate dehydratase | pFBA = -0.025271369124075814 | MOMA = 0.0 | absolute change = 0.025271369124075814
IPPMIb | 2-isopropylmalate hydratase | pFBA = -0.025271369124075814 | MOMA = 0.0 | absolute change = 0.025271369124075814
LEUTA | leucine transaminase | pFBA = -0.025271369124075814 | MOMA = 0.0 | absolute change = 0.025271369124075814
ARGSL | argininosuccinate lyase | pFBA = 0.02498419447493859 | MOMA = 0.0 | absolute change = 0.02498419447493859
ARGSSr | argininosuccinate synthase, reversible | pFBA = 0.02498419447493859 | MOMA = 0.0 | absolute change = 0.02498419447493859
OCBTi | ornithine carbamoyltransferase, irreversible | pFBA = 0.02498419447493859 | MOMA = 0.0 | absolute change = 0.02498419447493859
CITtcm | citrate transport, mitochondrial | pFBA = -0.02493766671164771 | MOMA = 0.0 | absolute change = 0.02493766671164771
DDPAm | 2-deoxy-D-arabino-heptulosonate 7-phosphate synthetase, mitochondrial | pFBA = 0.024122837976301922 | MOMA = 0.0 | absolute change = 0.024122837976301922
E4Ptm | D-erythrose 4-phosphate mtiochondrial transport via diffusion | pFBA = 0.024122837976301922 | MOMA = 0.0 | absolute change = 0.024122837976301922
2DDA7Ptm | 2-Dehydro-3-deoxy-D-arabino-heptonate7-phohsphate mitochondrial transport via diffusion | pFBA = -0.024122837976301922 | MOMA = 0.0 | absolute change = 0.024122837976301922
CITtbm | citrate transport, mitochondrial | pFBA = -0.024122837976301922 | MOMA = 0.0 | absolute change = 0.024122837976301922
CHORS | chorismate synthase | pFBA = 0.024122837976301922 | MOMA = 0.0 | absolute change = 0.024122837976301922
DHQS | 3-dehydroquinate synthase | pFBA = 0.024122837976301922 | MOMA = 0.0 | absolute change = 0.024122837976301922
DHQTi | 3-dehydroquinate dehydratase, irreversible | pFBA = 0.024122837976301922 | MOMA = 0.0 | absolute change = 0.024122837976301922
PSCVTi | 3-phosphoshikimate 1-carboxyvinyltransferase, irreversible | pFBA = 0.024122837976301922 | MOMA = 0.0 | absolute change = 0.024122837976301922
SHK3D | shikimate dehydrogenase | pFBA = 0.024122837976301922 | MOMA = 0.0 | absolute change = 0.024122837976301922
SHKK | shikimate kinase | pFBA = 0.024122837976301922 | MOMA = 0.0 | absolute change = 0.024122837976301922
ASADi | aspartate-semialdehyde dehydrogenase, irreversible | pFBA = 0.023917629502530683 | MOMA = 0.0 | absolute change = 0.023917629502530683
ASPKi | aspartate kinase, irreversible | pFBA = 0.023917629502530683 | MOMA = 0.0 | absolute change = 0.023917629502530683

CYTK1 | cytidylate kinase (CMP) | pFBA = -0.0030218593348001594 | MOMA = 0.0 | absolute change = 0.0030218593348001594
HSERTAm | homoserine O-trans-acetylase | pFBA = 0.002789780316006262 | MOMA = 0.0 | absolute change = 0.002789780316006262
ACHMStm | O-acetyl-L-homoserine mitochondrial permease | pFBA = -0.002789780316006262 | MOMA = 0.0 | absolute change = 0.002789780316006262
HOMtm | L-homoserine mitochondrial permease | pFBA = -0.0027897803160062615 | MOMA = 0.0 | absolute change = 0.0027897803160062615
AHSERL2 | O-acetylhomoserine (thiol)-lyase | pFBA = 0.002789696591618759 | MOMA = 0.0 | absolute change = 0.002789696591618759
GLYCERIDES | Diglycerides and triglycerides composition (mmol/mmol) | pFBA = 0.002557143732888859 | MOMA = 0.0 | absolute change = 0.002557143732888859
DAGPYP_PP | diacylglycerol pyrophosphate phosphatase, yeast-specific | pFBA = 0.0025260402568903053 | MOMA = 0.0 | absolute change = 0.0025260402568903053
NADHter | NADH transport into ER | pFBA = 0.0020862945224463148 | MOMA = 0.0 | absolute change = 0.0020862945224463148
NADter | NAD transport into ER | pFBA = -0.0020862945224463148 | MOMA = 0.0 | absolute change = 0.0020862945224463148
H2Oter | H2O endoplasmic reticulum transport | pFBA = -0.0020862945224463148 | MOMA = 0.0 | absolute change = 0.0020862945224463148
O2ter | O2  transport, endoplasmic reticulum | pFBA = 0.0020862945224463148 | MOMA = 0.0 | absolute change = 0.0020862945224463148
SQ23EPXter | Squalene-2,3-epoxide endoplamic reticular transport | pFBA = 0.0020862945224463148 | MOMA = 0.0 | absolute change = 0.0020862945224463148
SQLter | squalene endoplamic reticular transport | pFBA = 0.0020862945224463148 | MOMA = 0.0 | absolute change = 0.0020862945224463148
LNSTLS | lanosterol synthase | pFBA = 0.0020862945224463148 | MOMA = 0.0 | absolute change = 0.0020862945224463148
SQLErx | Squalene epoxidase, endoplasmic reticular (NAD) | pFBA = 0.0020862945224463148 | MOMA = 0.0 | absolute change = 0.0020862945224463148
SQLS | Squalene synthase | pFBA = 0.0020862945224463148 | MOMA = 0.0 | absolute change = 0.0020862945224463148
C3STDH2 | C-3 sterol dehydrogenase (zymosterol) | pFBA = 0.002076071679286328 | MOMA = 0.0 | absolute change = 0.002076071679286328
C3STKR2 | C-3 sterol keto reductase (zymosterol) | pFBA = 0.002076071679286328 | MOMA = 0.0 | absolute change = 0.002076071679286328
C4STMO2 | C-4 sterol methyl oxidase (4-methylzymosterol) | pFBA = 0.002076071679286328 | MOMA = 0.0 | absolute change = 0.002076071679286328
LNS14DMx | cytochrome P450 lanosterol 14-alpha-demethylase (NAD) | pFBA = 0.002076071679286328 | MOMA = 0.0 | absolute change = 0.002076071679286328
C14STR | C-14 sterol reductase | pFBA = 0.002076071679286328 | MOMA = 0.0 | absolute change = 0.002076071679286328
C3STDH1 | C-3 sterol dehydrogenase (4-methylzymosterol) | pFBA = 0.002076071679286328 | MOMA = 0.0 | absolute change = 0.002076071679286328
C3STKR1 | C-3 sterol keto reductase (4-methylzymosterol) | pFBA = 0.002076071679286328 | MOMA = 0.0 | absolute change = 0.002076071679286328
C4STMO1 | C-4 sterol methyl oxidase (4,4-dimethylzymosterol) | pFBA = 0.002076071679286328 | MOMA = 0.0 | absolute change = 0.002076071679286328
SAM24MT | S-adenosyl-methionine delta-24-sterol-c-methyltransferase | pFBA = 0.001997209746337857 | MOMA = 0.0 | absolute change = 0.001997209746337857
C8STI | C-8 sterol isomerase | pFBA = 0.0019646635517876947 | MOMA = 0.0 | absolute change = 0.0019646635517876947
NADPHter | NADPH transport into ER | pFBA = 0.0019321173572375322 | MOMA = 0.0 | absolute change = 0.0019321173572375322
NADPter | NADP transport into ER | pFBA = -0.0019321173572375322 | MOMA = 0.0 | absolute change = 0.0019321173572375322
ERGSTter | Ergosterol transport, ER | pFBA = 0.0019321173572375322 | MOMA = 0.0 | absolute change = 0.0019321173572375322
ERGTETROLter | Ergosta-5,6,22,24,(28)-tetraen-3beta-ol endoplamic reticular transport | pFBA = 0.0019321173572375322 | MOMA = 0.0 | absolute change = 0.0019321173572375322
C22STDSx | C-22 sterol desaturase (NAD) | pFBA = 0.0019321173572375322 | MOMA = 0.0 | absolute change = 0.0019321173572375322
C24STRer | C-s24 sterol reductase, endoplamic reticular | pFBA = 0.0019321173572375322 | MOMA = 0.0 | absolute change = 0.0019321173572375322
C5STDS | C-5 sterol desaturase | pFBA = 0.0019321173572375322 | MOMA = 0.0 | absolute change = 0.0019321173572375322
DESAT182 | Octadecadienoyl-CoA desaturase (n-C18:2CoA -> n-C18:3CoA) | pFBA = 0.001853621337632198 | MOMA = 0.0 | absolute change = 0.001853621337632198
STEROLS | Sterol composition (mmol/mmol) | pFBA = 0.0016759278095363453 | MOMA = 0.0 | absolute change = 0.0016759278095363453
TRIGS_PP | triglycerol synthesis | pFBA = 0.0016749291450422028 | MOMA = 0.0 | absolute change = 0.0016749291450422028
PPND2 | prephenate dehydrogenase (NADP) | pFBA = 0.007753715526705079 | MOMA = 0.009304458632046094 | absolute change = 0.0015507431053410148
DASYN_PP | CDP-Diacylglycerol synthetase, yeast-specific | pFBA = 0.0007245551780066784 | MOMA = 0.0 | absolute change = 0.0007245551780066784
PHOSPHOLIPIDS | Phospholipid composition (mmol/mmol) | pFBA = 0.0007212186188332027 | MOMA = 0.0 | absolute change = 0.0007212186188332027
PSERS_PP | phosphatidylserine synthase, yeast-specific | pFBA = 0.0006489525132261157 | MOMA = 0.0 | absolute change = 0.0006489525132261157
TRE6PP | trehalose-phosphatase | pFBA = 0.000607839053275876 | MOMA = 0.0 | absolute change = 0.000607839053275876
TRE6PS | alpha,alpha-trehalose-phosphate synthase (UDP-forming) | pFBA = 0.000607839053275876 | MOMA = 0.0 | absolute change = 0.000607839053275876
PSERDm_PP | phosphatidylserine decarboxylase, yeast-specific, mitochondrial | pFBA = 0.0006024339123113742 | MOMA = 0.0 | absolute change = 0.0006024339123113742
PStm_PP | phosphatidylserine mitochondrial  transport, yeast-specific | pFBA = 0.0006024339123113742 | MOMA = 0.0 | absolute change = 0.0006024339123113742
PEtm_PP | phosphatidylethanolamine mitochondrial transport, yeast-specific | pFBA = -0.0006024339123113742 | MOMA = 0.0 | absolute change = 0.0006024339123113742
CYSTH2SS | L-serine hydro-lyase (adding hydrogen sulfide, L-cysteine-forming) | pFBA = 0.000542237303511702 | MOMA = 0.0 | absolute change = 0.000542237303511702
STERYLEST | Steryl ester composition (mmol/mmol) | pFBA = 0.00041036671290996956 | MOMA = 0.0 | absolute change = 0.00041036671290996956
ERGSTAT_PP | Acyl-CoA:ergosterol acyltransferase, yeast-specific | pFBA = 0.0003800406128259228 | MOMA = 0.0 | absolute change = 0.0003800406128259228
PETOHM_PP | phosphatidylethanolamine N-methyltransferase, yeast-specific | pFBA = 0.0003653693523009005 | MOMA = 0.0 | absolute change = 0.0003653693523009005
PMETM_PP | Phosphatidyl-N-methylethanolamine N-methyltransferase, yeast-specific | pFBA = 0.0003653693523009005 | MOMA = 0.0 | absolute change = 0.0003653693523009005
MFAPS_PP | methylene-fatty-acyl-phospholipid synthase, yeast-specific | pFBA = 0.0003653693523009005 | MOMA = 0.0 | absolute change = 0.0003653693523009005
DESAT16 | Palmitoyl-CoA desaturase (n-C16:0CoA -> n-C16:1CoA) | pFBA = 0.0002858388044012268 | MOMA = 0.0 | absolute change = 0.0002858388044012268
RNDR4 | ribonucleoside-diphosphate reductase (UDP) | pFBA = 0.0001359600328670379 | MOMA = 0.0 | absolute change = 0.0001359600328670379
URIDK2r | uridylate kinase (dUMP) | pFBA = -0.0001359600328670379 | MOMA = 0.0 | absolute change = 0.0001359600328670379
DNA | DNA composition (mmol/g) - polymerization | pFBA = 8.372438750356419e-05 | MOMA = 0.0 | absolute change = 8.372438750356419e-05
DHFRi | dihydrofolate reductase (irreversible) | pFBA = 8.016610103466541e-05 | MOMA = 0.0 | absolute change = 8.016610103466541e-05
DADK | deoxyadenylate kinase | pFBA = -8.008237664715915e-05 | MOMA = 0.0 | absolute change = 8.008237664715915e-05
TMDS | thymidylate synthase | pFBA = 8.008237664715915e-05 | MOMA = 0.0 | absolute change = 8.008237664715915e-05
MI3PP | myo-inositol 3-phosphatase | pFBA = 7.56026647805627e-05 | MOMA = 0.0 | absolute change = 7.56026647805627e-05
MI3PS | 1D-myo-inositol-3-phosphate lyase (isomerizing) | pFBA = 7.56026647805627e-05 | MOMA = 0.0 | absolute change = 7.56026647805627e-05
PINOS_PP | phosphatidylinositol synthase, yeast-specific | pFBA = 7.56026647805627e-05 | MOMA = 0.0 | absolute change = 7.56026647805627e-05
FAE1_20 | Stearoyl-CoA:malonyl-CoA C-acyltransferase | pFBA = 5.800795382948271e-05 | MOMA = 0.0 | absolute change = 5.800795382948271e-05
FAE1_22 | Eicosanoyl-CoA:malonyl-CoA C-acyltransferase | pFBA = 5.800795382948271e-05 | MOMA = 0.0 | absolute change = 5.800795382948271e-05
FAE1_24 | Docosanoyl-CoA:malonyl-CoA C-acyltransferase | pFBA = 5.800795382948271e-05 | MOMA = 0.0 | absolute change = 5.800795382948271e-05
FAE2_20 | 3-Eicosanoyl-CoA reductase | pFBA = 5.800795382948271e-05 | MOMA = 0.0 | absolute change = 5.800795382948271e-05
FAE2_22 | 3-Docosanoyl-CoA reductase | pFBA = 5.800795382948271e-05 | MOMA = 0.0 | absolute change = 5.800795382948271e-05
FAE2_24 | 3-tetracosanoyl-CoA reductase | pFBA = 5.800795382948271e-05 | MOMA = 0.0 | absolute change = 5.800795382948271e-05
FAE3_20 | 3-Hydroxyeicosanoyl-CoA dehydrogenase | pFBA = 5.800795382948271e-05 | MOMA = 0.0 | absolute change = 5.800795382948271e-05
FAE3_22 | 3-Hydroxydocosanoyl-CoA dehydrogenase | pFBA = 5.800795382948271e-05 | MOMA = 0.0 | absolute change = 5.800795382948271e-05
FAE3_24 | 3-Hydroxytetracosanoyl-CoA dehydrogenase | pFBA = 5.800795382948271e-05 | MOMA = 0.0 | absolute change = 5.800795382948271e-05
FAE4_20 | (2E)-Eicosanoyl-CoA reductase | pFBA = 5.800795382948271e-05 | MOMA = 0.0 | absolute change = 5.800795382948271e-05
FAE4_22 | (2E)-Docosanoyl-CoA reductase | pFBA = 5.800795382948271e-05 | MOMA = 0.0 | absolute change = 5.800795382948271e-05
FAE4_24 | (2E)-tetracosanoyl-CoA reductase | pFBA = 5.800795382948271e-05 | MOMA = 0.0 | absolute change = 5.800795382948271e-05
GK2 | guanylate kinase (GMP:dATP) | pFBA = 5.61288293823895e-05 | MOMA = 0.0 | absolute change = 5.61288293823895e-05
RNTR1 | ribonucleoside-triphosphate reductase (ATP) | pFBA = 5.61288293823895e-05 | MOMA = 0.0 | absolute change = 5.61288293823895e-05
DCMPDA | dCMP deaminase | pFBA = -5.5877656219878737e-05 | MOMA = 0.0 | absolute change = 5.5877656219878737e-05
DGK1 | deoxyguanylate kinase (dGMP:ATP) | pFBA = -5.5877656219878737e-05 | MOMA = 0.0 | absolute change = 5.5877656219878737e-05
RNDR2 | ribonucleoside-diphosphate reductase (GDP) | pFBA = 5.5877656219878737e-05 | MOMA = 0.0 | absolute change = 5.5877656219878737e-05
FAE1_26 | tetracosanoyl-CoA:malonyl-CoA C-acyltransferase | pFBA = 4.428191230462756e-05 | MOMA = 0.0 | absolute change = 4.428191230462756e-05
FAE2_26 | 3-hexacosanoyl-CoA reductase | pFBA = 4.428191230462756e-05 | MOMA = 0.0 | absolute change = 4.428191230462756e-05
FAE3_26 | 3-Hydroxyhexacosanoyl-CoA dehydrogenase | pFBA = 4.428191230462756e-05 | MOMA = 0.0 | absolute change = 4.428191230462756e-05
FAE4_26 | (2E)-hexacosanoyl-CoA reductase | pFBA = 4.428191230462756e-05 | MOMA = 0.0 | absolute change = 4.428191230462756e-05
3DSPHR | 3-Dehydrosphinganine reductase | pFBA = 3.2002660849952624e-05 | MOMA = 0.0 | absolute change = 3.2002660849952624e-05
SERPT | serine C-palmitoyltransferase | pFBA = 3.2002660849952624e-05 | MOMA = 0.0 | absolute change = 3.2002660849952624e-05
SPHLIPIDS | Sphingolipid composition | pFBA = 3.199946090386224e-05 | MOMA = 0.0 | absolute change = 3.199946090386224e-05
RNDR1 | ribonucleoside-diphosphate reductase (ADP) | pFBA = 2.3953547264769654e-05 | MOMA = 0.0 | absolute change = 2.3953547264769654e-05
PSPHS | Phytosphingosine synthesis | pFBA = 2.3360826023273402e-05 | MOMA = 0.0 | absolute change = 2.3360826023273402e-05
PAtm_PP | phosphatidate reversible transport, mitochondrial, yeast-specific | pFBA = 1.9905633879796393e-05 | MOMA = 0.0 | absolute change = 1.9905633879796393e-05
DASYNm_PP | CDP-Diacylglycerol synthetase, yeast-specific, mitochondrial | pFBA = 1.9905633879796393e-05 | MOMA = 0.0 | absolute change = 1.9905633879796393e-05
CTPtm | CTP/CMP antiport | pFBA = 1.9905633879796393e-05 | MOMA = 0.0 | absolute change = 1.9905633879796393e-05
ZYMSTAT_PP | Acyl-CoA:zymosterol acyltransferase, yeast-specific | pFBA = 1.551186174799685e-05 | MOMA = 0.0 | absolute change = 1.551186174799685e-05
CERS224 | Ceramide-2 synthase (24C) | pFBA = 1.3726041524855154e-05 | MOMA = 0.0 | absolute change = 1.3726041524855154e-05
CERS324 | Ceramide-3 synthase (24C) | pFBA = 1.3506688548303112e-05 | MOMA = 0.0 | absolute change = 1.3506688548303112e-05
IPCS324_PP | Inositol phosphorylceramide synthase (ceramide-3, 24C), yeast-specific | pFBA = 1.2421950726922541e-05 | MOMA = 0.0 | absolute change = 1.2421950726922541e-05
CLPNtm | Cardiolipin transport to cytosol for phospholipid composition | pFBA = 9.952816939898197e-06 | MOMA = 0.0 | absolute change = 9.952816939898197e-06
CDPDGPm_PP | CDP-diacylglycerol--serine O-phosphatidyltransferae, yeast-specific, mitochondrial | pFBA = 9.952816939898197e-06 | MOMA = 0.0 | absolute change = 9.952816939898197e-06
CLPNSm_PP | cardiolipin synthase, yeast-specific, mitochondrial | pFBA = 9.952816939898197e-06 | MOMA = 0.0 | absolute change = 9.952816939898197e-06
GLYC3Ptmc | glycerol-3-phosphate shuttle | pFBA = 9.952816939898197e-06 | MOMA = 0.0 | absolute change = 9.952816939898197e-06
PGPPAm_PP | phosphatidylglycerol phosphate phosphatase A, yeast-specific, mitochondrial | pFBA = 9.952816939898197e-06 | MOMA = 0.0 | absolute change = 9.952816939898197e-06
CERS226 | Ceramide-2 synthase (26C) | pFBA = 9.634784498418248e-06 | MOMA = 0.0 | absolute change = 9.634784498418248e-06
CERS326 | Ceramide-3 synthase (26C) | pFBA = 9.497564282172462e-06 | MOMA = 0.0 | absolute change = 9.497564282172462e-06
MIPCS324_SC | mannose-inositol phosphorylceramide synthase (ceramide-3, 24C), yeast-specific | pFBA = 9.081437404677831e-06 | MOMA = 0.0 | absolute change = 9.081437404677831e-06
IPCS326_PP | Inositol phosphorylceramide synthase (ceramide-3, 26C), yeast-specific | pFBA = 8.802283707590808e-06 | MOMA = 0.0 | absolute change = 8.802283707590808e-06
PPNCL2 | phosphopantothenate-cysteine ligase | pFBA = 8.74550633907234e-06 | MOMA = 0.0 | absolute change = 8.74550633907234e-06
ASP1DC | aspartate 1-decarboxylase | pFBA = 8.74550633907234e-06 | MOMA = 0.0 | absolute change = 8.74550633907234e-06
DPCOAK | dephospho-CoA kinase | pFBA = 8.74550633907234e-06 | MOMA = 0.0 | absolute change = 8.74550633907234e-06
DPR | 2-dehydropantoate 2-reductase | pFBA = 8.74550633907234e-06 | MOMA = 0.0 | absolute change = 8.74550633907234e-06
MOHMT | 3-methyl-2-oxobutanoate hydroxymethyltransferase | pFBA = 8.74550633907234e-06 | MOMA = 0.0 | absolute change = 8.74550633907234e-06
PANTS | pantothenate synthase | pFBA = 8.74550633907234e-06 | MOMA = 0.0 | absolute change = 8.74550633907234e-06
PNTK | pantothenate kinase | pFBA = 8.74550633907234e-06 | MOMA = 0.0 | absolute change = 8.74550633907234e-06
PPCDC | phosphopantothenoylcysteine decarboxylase | pFBA = 8.74550633907234e-06 | MOMA = 0.0 | absolute change = 8.74550633907234e-06
PTPATi | pantetheine-phosphate adenylyltransferase | pFBA = 8.74550633907234e-06 | MOMA = 0.0 | absolute change = 8.74550633907234e-06
IPCavg | Average inositol phosphorylceramide | pFBA = 7.775868999638523e-06 | MOMA = 0.0 | absolute change = 7.775868999638523e-06
MIP2Cavg | Average mannose-(inositol-P)2-ceramide | pFBA = 7.775868999638523e-06 | MOMA = 0.0 | absolute change = 7.775868999638523e-06
MIPCavg | Average mannose-inositol phosphorylceramide | pFBA = 7.775868999638523e-06 | MOMA = 0.0 | absolute change = 7.775868999638523e-06
CERS118 | Ceramide-1 synthase (18C) | pFBA = 7.699717802560644e-06 | MOMA = 0.0 | absolute change = 7.699717802560644e-06
GLCCERavg | Average glucoceramide | pFBA = 7.049481237120851e-06 | MOMA = 0.0 | absolute change = 7.049481237120851e-06
CERS2d18 | Ceramide-2' synthase (18C) | pFBA = 6.4844157808001355e-06 | MOMA = 0.0 | absolute change = 6.4844157808001355e-06
EPISTAT_PP | Acyl-CoA:episterol acyltransferase, yeast-specific | pFBA = 6.401720721395525e-06 | MOMA = 0.0 | absolute change = 6.401720721395525e-06
FECOSTAT_PP | Acyl-CoA:fecosterol acyltransferase, yeast-specific | pFBA = 6.401720721395525e-06 | MOMA = 0.0 | absolute change = 6.401720721395525e-06
MIPCS326_SC | mannose-inositol phosphorylceramide synthase (ceramide-3, 26C), yeast-specific | pFBA = 5.93221045982423e-06 | MOMA = 0.0 | absolute change = 5.93221045982423e-06
MIP2CS324_PP | mannose-(inositol-P)2-ceramide synthase (ceramide-3, 24C), yeast specific | pFBA = 4.572988558687415e-06 | MOMA = 0.0 | absolute change = 4.572988558687415e-06
GLCCERS18m9 | Glucoceramide synthase (C18OH:2:9m) | pFBA = 4.239628510816851e-06 | MOMA = 0.0 | absolute change = 4.239628510816851e-06
CER9MET18 | Ceramide C9 methylase (C18OH:2) | pFBA = 4.239628510816851e-06 | MOMA = 0.0 | absolute change = 4.239628510816851e-06
MIP2CS326_PP | mannose-(inositol-P)2-ceramide synthase (ceramide-3, 26C), yeast-specific | pFBA = 3.1196786426549756e-06 | MOMA = 0.0 | absolute change = 3.1196786426549756e-06
LANOSTAT_PP | Acyl-CoA:lanosterol acyltransferase, yeast-specific | pFBA = 2.0107968932588507e-06 | MOMA = 0.0 | absolute change = 2.0107968932588507e-06
CERavg | Average ceramide | pFBA = 1.6255726139162017e-06 | MOMA = 0.0 | absolute change = 1.6255726139162017e-06
GLCCERS18d8 | Glucoceramide synthase (C18OH:2) | pFBA = 1.589023565659411e-06 | MOMA = 0.0 | absolute change = 1.589023565659411e-06
CER4DS2d18 | Ceramide delta-4 desaturase (C18OH) | pFBA = 6.328692740272136e-06 | MOMA = 7.594431288326563e-06 | absolute change = 1.265738548054427e-06
CER8DS2d18 | Ceramide delta-8 desaturase (C18OH:1) | pFBA = 5.892260732858803e-06 | MOMA = 7.0707128794305635e-06 | absolute change = 1.1784521465717604e-06
CERS116 | Ceramide-1 synthase (16C) | pFBA = 9.421170241185782e-07 | MOMA = 0.0 | absolute change = 9.421170241185782e-07
CERS2d16 | Ceramide-2' synthase (16C) | pFBA = 8.423393770764018e-07 | MOMA = 0.0 | absolute change = 8.423393770764018e-07
IPCS118_PP | Inositol phosphorylceramide synthase (ceramide-1, 18C), yeast-specific | pFBA = 7.736989654640331e-07 | MOMA = 0.0 | absolute change = 7.736989654640331e-07
MALSUCCtm | malate/succinate mitochondrial shuttle | pFBA = -6.697951000285135e-07 | MOMA = 0.0 | absolute change = 6.697951000285135e-07
5AOPtm | 5-Aminolevulinate mitochondrial transport | pFBA = -6.697951000222968e-07 | MOMA = 0.0 | absolute change = 6.697951000222968e-07
ALASm | 5-aminolevulinate synthase | pFBA = 6.697951000222968e-07 | MOMA = 0.0 | absolute change = 6.697951000222968e-07
CERS424 | Ceramide-4 synthase (24C) | pFBA = 6.415091924701783e-07 | MOMA = 0.0 | absolute change = 6.415091924701783e-07
IPCS424_PP | Inositol phosphorylceramide synthase (ceramide-4, 24C), yeast-specific | pFBA = 6.415091924701783e-07 | MOMA = 0.0 | absolute change = 6.415091924701783e-07
CERS426 | Ceramide-4 synthase (26C) | pFBA = 4.4944522817910664e-07 | MOMA = 0.0 | absolute change = 4.4944522817910664e-07
IPCS426_PP | Inositol phosphoryceramide synthase (ceramide-4, 26C), yeast-specific | pFBA = 4.4944522817910664e-07 | MOMA = 0.0 | absolute change = 4.4944522817910664e-07
GLCCERS16d8 | Glucoceramide synthase (C16OH:2) | pFBA = 4.179637425488953e-07 | MOMA = 0.0 | absolute change = 4.179637425488953e-07
GLCCERS16m9 | Glucoceramide synthase (C16OH:2:9m) | pFBA = 4.0590912963341857e-07 | MOMA = 0.0 | absolute change = 4.0590912963341857e-07
CER9MET16 | Ceramide C9 methylase (C16OH:2) | pFBA = 4.0590912963341857e-07 | MOMA = 0.0 | absolute change = 4.0590912963341857e-07
MIPCS424_SC | mannose-inositol phosphorylceramide synthase (ceramide-4, 24C), yeast-specific | pFBA = 3.5846756088333593e-07 | MOMA = 0.0 | absolute change = 3.5846756088333593e-07
DB4PS | 3,4-Dihydroxy-2-butanone-4-phosphate synthase | pFBA = 3.3489755001425675e-07 | MOMA = 0.0 | absolute change = 3.3489755001425675e-07

# Version with Randomness

In [22]:
increase_min = 0.05   # 5%
increase_max = 0.10   # 10%

flux_threshold = 1e-6

# Increase NADPH-producing reactions + MOMA

nadph_c = model.metabolites.get_by_id("nadph_c")

with model:

    # Identify NADPH-producing reactions
    nadph_producing_reactions = []

    for reaction in model.reactions:

        nadph_stoich = reaction.metabolites.get(nadph_c, 0)
        reference_flux = pfba_WT.fluxes[reaction.id]

        # Only reactions that actually produce NADPH
        # in the pFBA_WT solution
        if reference_flux * nadph_stoich > 0:

            # Random increase between 5 and 20%
            increase = np.random.uniform(
                increase_min,
                increase_max
            )

            target_flux = reference_flux * (1 + increase)

            nadph_producing_reactions.append({
                "ID": reaction.id,
                "Name": reaction.name,
                "Reference flux": reference_flux,
                "NADPH stoichiometry": nadph_stoich,
                "Increase": increase,
                "Target flux": target_flux
            })

            # Set new lower bound
            reaction.lower_bound = target_flux

    moma_result = cobra.flux_analysis.moma(
        model,
        solution=pfba_WT,
        linear=True
    )
    
# Calculate flux changes

reaction_changes = []

for reaction in model.reactions:

    reaction_id = reaction.id

    reference_flux = pfba_WT.fluxes[reaction_id]
    moma_flux = moma_result.fluxes[reaction_id]

    absolute_change = abs(
        moma_flux - reference_flux
    )

    # Avoid division by zero 
    if abs(reference_flux) > flux_threshold:

        proportional_change = (
            absolute_change / abs(reference_flux)
        )

    else:

        proportional_change = np.nan

    reaction_changes.append({
        "ID": reaction_id,
        "Name": reaction.name,
        "pFBA flux": reference_flux,
        "MOMA flux": moma_flux,
        "Absolute change": absolute_change,
        "Proportional change": proportional_change
    })

# Top 10 proportional changes


proportional_changes = sorted(
    [
        r for r in reaction_changes
        if abs(r["pFBA flux"]) > flux_threshold
    ],
    key=lambda x: x["Proportional change"],
    reverse=True
)

print("\n===== TOP 10 PROPORTIONAL CHANGES =====\n")

for r in proportional_changes[:10]:

    print(
        r["ID"],
        "|", r["Name"],
        "| pFBA =", round(r["pFBA flux"], 6),
        "| MOMA =", round(r["MOMA flux"], 6),
        "| change =",
        round(r["Proportional change"] * 100, 2),
        "%"
    )

# Top 10 absolute changes

absolute_changes = sorted(
    reaction_changes,
    key=lambda x: x["Absolute change"],
    reverse=True
)

print("\n===== TOP 10 ABSOLUTE CHANGES =====\n")

for r in absolute_changes[:10]:

    print(
        r["ID"],
        "|", r["Name"],
        "| pFBA =", round(r["pFBA flux"], 6),
        "| MOMA =", round(r["MOMA flux"], 6),
        "| absolute change =",
        round(r["Absolute change"], 6)
    )

# Save reaction IDs to Excel

proportional_ids = [
    r["ID"] for r in proportional_changes[:10]
]

absolute_ids = [
    r["ID"] for r in absolute_changes[:10]
]

with pd.ExcelWriter(
    "RDXMAX_it.xlsx",
    engine="openpyxl"
) as writer:

    pd.DataFrame({
        "Reaction ID": proportional_ids
    }).to_excel(
        writer,
        sheet_name="Top 10 Proportional",
        index=False
    )

    pd.DataFrame({
        "Reaction ID": absolute_ids
    }).to_excel(
        writer,
        sheet_name="Top 10 Absolute",
        index=False
    )

print("\nResults saved to RDXMAX_it.xlsx")

===== TOP 10 PROPORTIONAL CHANGES =====

DPR | 2-dehydropantoate 2-reductase | pFBA = 9e-06 | MOMA = 0.012848 | change = 146815.04 %
FAE1_22 | Eicosanoyl-CoA:malonyl-CoA C-acyltransferase | pFBA = 5.8e-05 | MOMA = 0.004295 | change = 7303.65 %
FAE2_22 | 3-Docosanoyl-CoA reductase | pFBA = 5.8e-05 | MOMA = 0.004295 | change = 7303.65 %
FAE3_22 | 3-Hydroxydocosanoyl-CoA dehydrogenase | pFBA = 5.8e-05 | MOMA = 0.004295 | change = 7303.65 %
FAE4_22 | (2E)-Docosanoyl-CoA reductase | pFBA = 5.8e-05 | MOMA = 0.004295 | change = 7303.65 %
PSERS_PP | phosphatidylserine synthase, yeast-specific | pFBA = 0.000649 | MOMA = 0.025487 | change = 3827.48 %
DASYN_PP | CDP-Diacylglycerol synthetase, yeast-specific | pFBA = 0.000725 | MOMA = 0.028081 | change = 3775.67 %
PINOS_PP | phosphatidylinositol synthase, yeast-specific | pFBA = 7.6e-05 | MOMA = 0.002594 | change = 3330.93 %
FAE1_26 | tetracosanoyl-CoA:malonyl-CoA C-acyltransferase | pFBA = 4.4e-05 | MOMA = 0.001365 | change = 2981.75 %
FAE2_26 | 3-hexacosanoyl-CoA reductase | pFBA = 4.4e-05 | MOMA = 0.001365 | change = 2981.75 %

===== TOP 10 ABSOLUTE CHANGES =====

ABTDG | D-arabinitol dehydrogenase (D-xyulose-forming) | pFBA = 0.0 | MOMA = -0.04651 | absolute change = 0.04651
XYLK | xylulokinase | pFBA = 0.0 | MOMA = 0.04651 | absolute change = 0.04651
RU5PP | Ribulose 5-phosphatase | pFBA = 0.0 | MOMA = 0.04651 | absolute change = 0.04651
DABTDHR | D-arabitol dehydrogenase (D-ribulose-forming) | pFBA = 0.0 | MOMA = 0.04651 | absolute change = 0.04651
ASNNe | L-asparaginase, extracellular | pFBA = 0.0 | MOMA = -0.035879 | absolute change = 0.035879
ASNt2r | L-asparagine reversible transport via proton symport | pFBA = 0.0 | MOMA = 0.035879 | absolute change = 0.035879
ASPt2r | L-aspartate reversible transport via proton symport | pFBA = 0.0 | MOMA = -0.035879 | absolute change = 0.035879
ASNS1 | asparagine synthase (glutamine-hydrolysing) | pFBA = 0.015959 | MOMA = -0.019739 | absolute change = 0.035698
PYRDC | pyruvate decarboxylase | pFBA = 0.227314 | MOMA = 0.192646 | absolute change = 0.034668
PIPLC | phosphatidylinositol phospholipase C | pFBA = 0.0 | MOMA = 0.033532 | absolute change = 0.033532

Results saved to RDXMAX_it.xlsx

In [23]:
moma_result.fluxes['Ex_biomass']

0.08467202417038147

In [24]:
# NADPH turnover rate WT strain

positive_nadph_flux_sum_WT = 0.0
for reaction in nadph_c.reactions:
    flux = pfba_WT.fluxes[reaction.id]
    coef = reaction.get_coefficient(nadph_c)
    # No totes les reaccions tenen 1 de coeficient estequiomètric pel cofactor
    #independentment si s'està produint o consumint
    positive_nadph_flux_sum_WT += abs(flux*coef)
    

print (positive_nadph_flux_sum_WT/2)

0.8110824311896001

In [25]:
# NADPH turnover rate mutant strain

positive_nadph_flux_sum_moma = 0.0
for reaction in nadph_c.reactions:
    flux = moma_result.fluxes[reaction.id]
    coef = reaction.get_coefficient(nadph_c)
    # No totes les reaccions tenen 1 de coeficient estequiomètric pel cofactor
    #independentment si s'està produint o consumint
    positive_nadph_flux_sum_moma += abs(flux*coef)
    

print (positive_nadph_flux_sum_moma/2)

0.8913940605094128

In [26]:
#Set the number of iterations to run

n_iterations = 20

proportional_results = []
absolute_results = []

for iteration in range(1, n_iterations + 1):

    # 1. Randomly increase each NADPH-producing reaction between a 5 and 10 %

    increase_min = 0.05
    increase_max = 0.10

    nadph_c = model.metabolites.get_by_id("nadph_c")

    with model:

        for reaction in model.reactions:

            nadph_stoich = reaction.metabolites.get(nadph_c, 0)
            reference_flux = pfba_WT.fluxes[reaction.id]

            if reference_flux * nadph_stoich > 0:

                increase = np.random.uniform(
                    increase_min,
                    increase_max
                )

                target_flux = reference_flux * (1 + increase)

                reaction.lower_bound = target_flux
       
        # 2. MOMA using pFBA_WT as reference
    
        moma_result = cobra.flux_analysis.moma(
            model,
            solution=pfba_WT,
            linear=True
        )

        # 3. Calculate changes

        reaction_changes = []

        for reaction in model.reactions:

            reaction_id = reaction.id

            reference_flux = pfba_WT.fluxes[reaction_id]
            moma_flux = moma_result.fluxes[reaction_id]

            absolute_change = abs(
                moma_flux - reference_flux
            )

            if abs(reference_flux) > 1e-6:

                proportional_change = (
                    absolute_change / abs(reference_flux)
                )

            else:

                proportional_change = np.nan

            reaction_changes.append({
                "ID": reaction_id,
                "Name": reaction.name,
                "pFBA flux": reference_flux,
                "MOMA flux": moma_flux,
                "Absolute change": absolute_change,
                "Proportional change": proportional_change
            })

        # 4. Top 10 proportional changes

        proportional_changes = sorted(
            [
                r for r in reaction_changes
                if not np.isnan(r["Proportional change"])
            ],
            key=lambda x: x["Proportional change"],
            reverse=True
        )

        # Use reaction IDs instead of names
        proportional_ids = [
            r["ID"] for r in proportional_changes[:10]
        ]

        # 5. Top 10 absolute changes

        absolute_changes = sorted(
            reaction_changes,
            key=lambda x: x["Absolute change"],
            reverse=True
        )

        # Use reaction IDs instead of names
        absolute_ids = [
            r["ID"] for r in absolute_changes[:10]
        ]

    # 6. Store results from this iteration

    proportional_results.append(
        [iteration] + proportional_ids
    )

    absolute_results.append(
        [iteration] + absolute_ids
    )

    print(f"Iteration {iteration}/{n_iterations} completed")

# 7. Create Excel file

columns = ["Iteration"] + [
    f"Top {i}" for i in range(1, 11)
]

df_proportional = pd.DataFrame(
    proportional_results,
    columns=columns
)

df_absolute = pd.DataFrame(
    absolute_results,
    columns=columns
)


with pd.ExcelWriter(
    "RDXMAX_results.xlsx",
    engine="openpyxl"
) as writer:

    df_proportional.to_excel(
        writer,
        sheet_name="Proportional changes",
        index=False
    )

    df_absolute.to_excel(
        writer,
        sheet_name="Absolute changes",
        index=False
    )

print("Excel file created: RDXMAX_results.xlsx")

Iteration 1/20 completed
Iteration 2/20 completed
Iteration 3/20 completed
Iteration 4/20 completed
Iteration 5/20 completed
Iteration 6/20 completed
Iteration 7/20 completed
Iteration 8/20 completed
Iteration 9/20 completed
Iteration 10/20 completed
Iteration 11/20 completed
Iteration 12/20 completed
Iteration 13/20 completed
Iteration 14/20 completed
Iteration 15/20 completed
Iteration 16/20 completed
Iteration 17/20 completed
Iteration 18/20 completed
Iteration 19/20 completed
Iteration 20/20 completed
Excel file created: RDXMAX_results.xlsx

### The next step is to count the number of times that reactions appear in the lists

In [27]:
from collections import Counter

# Remove the Iteration column
proportional_ids = df_proportional.drop(columns=["Iteration"]).values.flatten()
absolute_ids = df_absolute.drop(columns=["Iteration"]).values.flatten()

# Count occurrences
proportional_counts = Counter(proportional_ids)
absolute_counts = Counter(absolute_ids)

# Convert to DataFrames and sort
df_proportional_counts = pd.DataFrame(
    proportional_counts.items(),
    columns=["Reaction ID", "Occurrences"]
).sort_values(
    "Occurrences",
    ascending=False
)

df_absolute_counts = pd.DataFrame(
    absolute_counts.items(),
    columns=["Reaction ID", "Occurrences"]
).sort_values(
    "Occurrences",
    ascending=False
)

print("\n===== PROPORTIONAL CHANGE FREQUENCY =====\n")
print(df_proportional_counts)

print("\n===== ABSOLUTE CHANGE FREQUENCY =====\n")
print(df_absolute_counts)

===== PROPORTIONAL CHANGE FREQUENCY =====

    Reaction ID  Occurrences
19         TKT2            6
8      DASYN_PP            6
21     CYSTH2SS            6
0        DPCOAK            4
1        PTPATi            4
..          ...          ...
61     HMGCOASm            1
62          HSK            1
63         THRS            1
64        DHFRi            1
101     FAE2_16            1

[102 rows x 2 columns]

===== ABSOLUTE CHANGE FREQUENCY =====

    Reaction ID  Occurrences
30        H2Otm            7
5        ATPS3m            4
31        PIt2m            4
119       MTHFC            4
120       MTHFD            4
..          ...          ...
52      DPCOAKm            1
50       COAtim            1
47       CITtcm            1
46       CITtam            1
143         PGK            1

[144 rows x 2 columns]

In [28]:
# Transfer the results into an Excel file
with pd.ExcelWriter(
    "RDXMAX_frecuencies.xlsx",
    engine="openpyxl"
) as writer:

    df_proportional.to_excel(
        writer,
        sheet_name="Proportional changes",
        index=False
    )

    df_absolute.to_excel(
        writer,
        sheet_name="Absolute changes",
        index=False
    )

    df_proportional_counts.to_excel(
        writer,
        sheet_name="Proportional frequency",
        index=False
    )

    df_absolute_counts.to_excel(
        writer,
        sheet_name="Absolute frequency",
        index=False
    )