In [1]:
import cobra
import escher
import pandas as pd
import numpy as np
import json
import csv
from cobra.io import save_json_model
from cobra import Reaction
from cobra.flux_analysis.loopless import add_loopless, loopless_solution
import matplotlib.pyplot as plt
from cobra.sampling import OptGPSampler
from scipy.stats import gaussian_kde
import matplotlib.pyplot as plt
import os
from scipy.stats import linregress

In [2]:
cobra.Configuration().solver = "gurobi"

In [3]:
# model_path = './models/iMT1026v3.xml'
model_path = './models/iMT1026v3jup.xml'

model = cobra.io.read_sbml_model(model_path)

model

Set parameter Username
Academic license - for non-commercial use only - expires 2027-09-18

In [4]:
# Change grwoth on glycerol to growth on 60% glucose and 40% methanol
# Add reaction describing this growth

biomass_gly = model.reactions.get_by_id('BIOMASS_glyc')
biomass_gly.bounds = (0,0)
biomass_gly

carbs = model.metabolites.get_by_id('CARBOHYDRATES_c')
DNA = model.metabolites.get_by_id('DNA_c')
lipids = model.metabolites.get_by_id('LIPIDS_c')
prot = model.metabolites.get_by_id('PROTEIN_c')
RNA = model.metabolites.get_by_id('RNA_c')
atp = model.metabolites.get_by_id('atp_c')
cof = model.metabolites.get_by_id('cof_c')
h2o = model.metabolites.get_by_id('h2o_c')
adp = model.metabolites.get_by_id('adp_c')
biomass = model.metabolites.get_by_id('biomass_c')
h = model.metabolites.get_by_id('h_c')
pi = model.metabolites.get_by_id('pi_c')

biomass_glc_meoh = Reaction ('biomass_glc_meoh_60/40')
biomass_glc_meoh.name = 'Biomass composition (g/g) - 60/40 Glucose/Methanol'
biomass_glc_meoh.add_metabolites({carbs: -0.33,
                                   DNA: -0.001,
                                   lipids: -0.042,
                                   prot: -0.49,
                                   RNA: -0.058,
                                   atp: -63.85,
                                   cof: -1,
                                   h2o: -63.85,
                                   adp: 63.85,
                                   pi: 63.85,
                                   biomass: 1,
                                   h: 63.85})
biomass_glc_meoh

In [5]:
# Add new biomass reaction to the model

print (len(model.reactions))
model.add_reactions([biomass_glc_meoh])
print (len(model.reactions))

2237
2238

In [6]:
#Tanquem l'entrada de Glicerol
glycerol_exchange = model.exchanges.get_by_id('Ex_glyc')
glycerol_exchange.bounds = (0,0)
glycerol_exchange

In [7]:
# Add qmeoh constraints observed in chemostat cultivations from Sergi Monforte's doctoral thesis
methanol_exchange = model.exchanges.get_by_id('Ex_meoh')
methanol_exchange.bounds = (-1.24, -1.18)
methanol_exchange

In [8]:
# Add qgluc constraints observed in chemostat cultivations from Sergi Monforte's doctoral thesis
glucose_exchange = model.reactions.get_by_id('Ex_glc_D')
glucose_exchange.bounds = (-0.72, -0.7)
glucose_exchange

In [9]:
# Change the reactions for the synthesis of lipids, proteins and sterols from glycerol to those from glucose

model.reactions.get_by_id('LIPIDS_glyc').bounds = (0,0)
model.reactions.get_by_id('PROTEINS_glyc').bounds = (0,0)
model.reactions.get_by_id('STEROLS_glyc').bounds = (0,0)

# note: these reactions from glucose do not have the glucose specification
model.reactions.get_by_id('LIPIDS').bounds = (0,1000)
model.reactions.get_by_id('PROTEINS').bounds = (0,1000)
model.reactions.get_by_id('STEROLS').bounds = (0,1000)

In [10]:
# ATP maintenance requirement (NGAME = Non-Growth Associated Maintenance Energy) based on previous studies on 
# the growth of X33-ROL on Gluc/MeOH from the group (Eric's Master Thesis)

model.reactions.get_by_id('ATPM').bounds = (1.96, 1000)

In [11]:
rolAA = model.reactions.get_by_id('rolAA')
rolAA.bounds = (0,1000)
rolRNA = model.reactions.get_by_id('rolRNA')
rolRNA.bounds = (0,1000)
rolDNA = model.reactions.get_by_id('rolDNA')
rolDNA.bounds = (0,1000)
pROL = model.reactions.get_by_id('pROL')
pROL.bounds = (0,1000)
Rol_transport =  model.reactions.get_by_id('ROLt')
Rol_transport.bounds = (0,1000)
ROL_exchange = model.exchanges.get_by_id('Ex_rol')
ROL_exchange.bounds = (0,1000) #Value obtained from calculations of data from previous studies in our research group

pFAB = model.reactions.get_by_id('pFAB')
pFAB.bounds = (0,0)
fabAA = model.reactions.get_by_id('fabAA')
fabAA.bounds = (0,0)
fabt = model.reactions.get_by_id('fabt')
fabt.bounds = (0,0)
fabRNA = model.reactions.get_by_id('fabRNA')
fabRNA.bounds = (0,0)
fabDNA = model.reactions.get_by_id('fabDNA')
FAB_exchange = model.exchanges.get_by_id('Ex_fab')
FAB_exchange.bounds = (0,0)


# Extra reactions that must be closed for simulations to run smoothly:

APAT2r = model.reactions.get_by_id('APAT2r')
APAT2r.bounds = (0,0) # reaction not present in Pichia, it is yet to be removed from the model

MMSAD3 = model.reactions.get_by_id('MMSAD3')
MMSAD3.bounds = (0,0) # The reduction reaction of MSA into Acetil-CoA it is due to an unspecific effect. Reaction
# under evaluation of being kept or not.

## Reaction Ratios as constraints

### The experimental data was extracted from the paper:
#### "Metabolic flux analysis of recombinant Pichia pastoris growing on different glycerol/methanol mixtures by iterative fitting of NMR-derived 13C labelling data from proteinogenic amino acids" by Joel Jordà, 2014

In [12]:
ReactionRatio1 = model.problem.Constraint(model.reactions.CSm.flux_expression - model.reactions.ACONTm.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio1)

ReactionRatio2 = model.problem.Constraint(model.reactions.AKGDam.flux_expression - model.reactions.FUMm.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio2)

ReactionRatio8 = model.problem.Constraint(68*model.reactions.AKGDam.flux_expression - 46*model.reactions.CSm.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio8)

ReactionRatio9 = model.problem.Constraint(model.reactions.G6PDH2.flux_expression - model.reactions.GND.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio9)

ReactionRatio10 = model.problem.Constraint(0.8*model.reactions.MDHm.flux_expression - model.reactions.FUMm.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio10)

ReactionRatio12 = model.problem.Constraint(35*model.reactions.PYK.flux_expression - 143*model.reactions.PC.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio12)

ReactionRatio13 = model.problem.Constraint(68*model.reactions.PYK.flux_expression - 143*model.reactions.PYRt2m.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio13)


ReactionRatio14 = model.problem.Constraint(40*model.reactions.GAPD.flux_expression - 145*model.reactions.FBA.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio14)


ReactionRatio16 = model.problem.Constraint(model.reactions.GAPD.flux_expression - model.reactions.PYK.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio16)

ReactionRatio20 = model.problem.Constraint(0.18*model.reactions.FALDtx.flux_expression - 0.82*model.reactions.DAS.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio20)

ReactionRatio21 = model.problem.Constraint(model.reactions.G6PDH2.flux_expression + 0.4*model.reactions.Ex_glc_D.flux_expression,
                                         lb=0,
                                         ub=0)
model.add_cons_vars(ReactionRatio21)

In [13]:
#WT Rol producer strain reference flux distribution
pfba_WT = cobra.flux_analysis.pfba(model)

In [14]:
ROL_exchange.bounds = (0.003, 1000)

In [15]:
pfba_WT_RolProd = cobra.flux_analysis.pfba(model)

In [16]:
pfba_WT.fluxes['Ex_rol']

0.0

In [17]:
pfba_WT_RolProd.fluxes['Ex_rol']

0.003

In [18]:
#Obtain reference value for growth rate
RefGrowthRate = pfba_WT.fluxes['Ex_biomass']
RefGrowthRate

0.08372440263613617

## MOMA Simulations

### Carbon Source: Glc/MeOH

In [19]:
# Remove Reaction Ratio Constraints before starting MOMA simulations

ReactionRatioList = [ReactionRatio1, ReactionRatio2, ReactionRatio8, ReactionRatio9, ReactionRatio10,
                     ReactionRatio12, ReactionRatio13, ReactionRatio14, ReactionRatio16, ReactionRatio20, ReactionRatio21]
                    

model.remove_cons_vars(ReactionRatioList)

In [20]:
Growth = model.reactions.get_by_id("Ex_biomass")
ROL_exchange = model.reactions.get_by_id("Ex_rol")

WT_fluxes = pfba_WT.fluxes.copy()

RefGrowthRate = WT_fluxes["Ex_biomass"]

print("WT growth rate:", RefGrowthRate)


# ============================================================
# 2. PRODUCTION CONDITION
# ============================================================

Growth.bounds = (RefGrowthRate * 0.9, RefGrowthRate * 0.9)

ROL_exchange.bounds = (0, 1000)

model.objective = "Ex_rol"

print("Growth fixed at:", RefGrowthRate * 0.9)
print("Objective:", model.objective.expression)


# ============================================================
# 3. MOMA
# ============================================================

moma_result = cobra.flux_analysis.moma(
    model,
    pfba_WT,
    0
)

print("\nMOMA completed.")


# ============================================================
# 4. pFBA
# ============================================================

pfba_RolObj = cobra.flux_analysis.pfba(model)

print("pFBA completed.")


# ============================================================
# 5. CREATE COMPARISON TABLE
# ============================================================

results = pd.DataFrame({
    "WT": WT_fluxes,
    "MOMA": moma_result.fluxes,
    "pFBA_RolObj": pfba_RolObj.fluxes
})


# ============================================================
# 6. SIGNED FLUX CHANGES
# ============================================================

results["Delta_MOMA"] = (
    results["MOMA"] - results["WT"]
)

results["Delta_pFBA_RolObj"] = (
    results["pFBA_RolObj"] - results["WT"]
)


# ============================================================
# 7. ABSOLUTE FLUX CHANGES
# ============================================================

results["Abs_Delta_MOMA"] = (
    results["Delta_MOMA"].abs()
)

results["Abs_Delta_pFBA_RolObj"] = (
    results["Delta_pFBA_RolObj"].abs()
)


# ============================================================
# 8. RELATIVE FLUX CHANGES
# ============================================================

eps = 1e-9

results["Relative_MOMA"] = (
    results["Delta_MOMA"] /
    results["WT"].abs().clip(lower=eps)
)

results["Relative_pFBA_RolObj"] = (
    results["Delta_pFBA_RolObj"] /
    results["WT"].abs().clip(lower=eps)
)


# ============================================================
# 9. REACTION INFORMATION
# ============================================================

results["Reaction"] = results.index

results["Name"] = [
    model.reactions.get_by_id(reaction).name
    for reaction in results.index
]

results["Genes"] = [
    ", ".join(
        gene.id
        for gene in model.reactions.get_by_id(reaction).genes
    )
    for reaction in results.index
]


# ============================================================
# 10. FILTER
# ============================================================

results = results[
    ~results["Reaction"].str.startswith("Ex_")
]

results = results[
    results["Genes"].str.len() > 0
]


# ============================================================
# 11. DETERMINE FLUX DIRECTION
# ============================================================

def get_direction(value, threshold=1e-9):

    if value > threshold:
        return "↑"

    elif value < -threshold:
        return "↓"

    else:
        return "–"


results["Direction_MOMA"] = (
    results["Delta_MOMA"]
    .apply(get_direction)
)

results["Direction_pFBA_RolObj"] = (
    results["Delta_pFBA_RolObj"]
    .apply(get_direction)
)


# ============================================================
# 12. DETERMINE CONSENSUS
# ============================================================

def determine_consensus(row):

    moma = row["Direction_MOMA"]
    pfba = row["Direction_pFBA_RolObj"]

    if moma == "↑" and pfba == "↑":
        return "↑ Consistent"

    elif moma == "↓" and pfba == "↓":
        return "↓ Consistent"

    elif moma == "–" and pfba == "–":
        return "No change"

    else:
        return "Discordant"


results["Consensus"] = results.apply(
    determine_consensus,
    axis=1
)


# ============================================================
# 13. RANKING AND SCORING
# ============================================================

# Rank 1  -> 20 points
# Rank 2  -> 19 points
# ...
# Rank 20 -> 1 point
# Rank >20 -> 0 points


# MOMA absolute ranking
results["MOMA_Abs_Rank"] = (
    results["Abs_Delta_MOMA"]
    .rank(
        method="min",
        ascending=False
    )
)

results["MOMA_Abs_Rank"] = (
    results["MOMA_Abs_Rank"]
    .astype(int)
)

results["MOMA_Abs_Score"] = (
    21 - results["MOMA_Abs_Rank"]
).clip(lower=0, upper=20)


# MOMA relative ranking
results["MOMA_Rel_Rank"] = (
    results["Relative_MOMA"].abs()
    .rank(
        method="min",
        ascending=False
    )
)

results["MOMA_Rel_Rank"] = (
    results["MOMA_Rel_Rank"]
    .astype(int)
)

results["MOMA_Rel_Score"] = (
    21 - results["MOMA_Rel_Rank"]
).clip(lower=0, upper=20)


# pFBA absolute ranking
results["pFBA_Abs_Rank"] = (
    results["Abs_Delta_pFBA_RolObj"]
    .rank(
        method="min",
        ascending=False
    )
)

results["pFBA_Abs_Rank"] = (
    results["pFBA_Abs_Rank"]
    .astype(int)
)

results["pFBA_Abs_Score"] = (
    21 - results["pFBA_Abs_Rank"]
).clip(lower=0, upper=20)


# pFBA relative ranking
results["pFBA_Rel_Rank"] = (
    results["Relative_pFBA_RolObj"].abs()
    .rank(
        method="min",
        ascending=False
    )
)

results["pFBA_Rel_Rank"] = (
    results["pFBA_Rel_Rank"]
    .astype(int)
)

results["pFBA_Rel_Score"] = (
    21 - results["pFBA_Rel_Rank"]
).clip(lower=0, upper=20)


# Total score
results["Total_Score"] = (
    results["MOMA_Abs_Score"] +
    results["MOMA_Rel_Score"] +
    results["pFBA_Abs_Score"] +
    results["pFBA_Rel_Score"]
)


# ============================================================
# 14. REORDER COLUMNS
# ============================================================

results = results[
    [
        "Reaction",
        "Name",
        "Genes",

        "WT",

        "MOMA",
        "Delta_MOMA",
        "Abs_Delta_MOMA",
        "Relative_MOMA",
        "Direction_MOMA",
        "MOMA_Abs_Rank",
        "MOMA_Abs_Score",
        "MOMA_Rel_Rank",
        "MOMA_Rel_Score",

        "pFBA_RolObj",
        "Delta_pFBA_RolObj",
        "Abs_Delta_pFBA_RolObj",
        "Relative_pFBA_RolObj",
        "Direction_pFBA_RolObj",
        "pFBA_Abs_Rank",
        "pFBA_Abs_Score",
        "pFBA_Rel_Rank",
        "pFBA_Rel_Score",

        "Consensus",
        "Total_Score"
    ]
]


# ============================================================
# 15. SORT BY TOTAL SCORE
# ============================================================

results_sorted = results.sort_values(
    [
        "Total_Score",
        "Consensus"
    ],
    ascending=[
        False,
        True
    ]
)


# ============================================================
# 16. DISPLAY
# ============================================================

pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

display(results_sorted)

# Export the complete consistent-candidates table to Excel

consistent_candidates = results_sorted[
    results_sorted["Consensus"].isin(
        [
            "↑ Consistent",
            "↓ Consistent"
        ]
    )
]

# ============================================================
# 18. RESTORE MODEL TO WT STATE
# ============================================================

ROL_exchange.bounds = (0, 1000)
Growth.bounds = (0, 1000)
model.objective = "Ex_biomass"

WT growth rate: 0.08372440263613617
Growth fixed at: 0.07535196237252256
Objective: 1.0*Ex_rol - 1.0*Ex_rol_reverse_f88d3

MOMA completed.
pFBA completed.

,Reaction,Name,Genes,WT,MOMA,Delta_MOMA,Abs_Delta_MOMA,Relative_MOMA,Direction_MOMA,MOMA_Abs_Rank,MOMA_Abs_Score,MOMA_Rel_Rank,MOMA_Rel_Score,pFBA_RolObj,Delta_pFBA_RolObj,Abs_Delta_pFBA_RolObj,Relative_pFBA_RolObj,Direction_pFBA_RolObj,pFBA_Abs_Rank,pFBA_Abs_Score,pFBA_Rel_Rank,pFBA_Rel_Score,Consensus,Total_Score
NTP1,NTP1,ATPase,"PAS_chr4_0736, PAS_chr1-1_0428, PAS_chr3_0731,...",0.000000,0.009170,0.009170,0.009170,9.169709e+06,↑,4,17,1,20,0.000000,0.000000,0.000000,0.000000e+00,–,466,0,466,0,Discordant,37
ATPH1,ATPH1,ATP diphosphohydrolase,PAS_chr1-1_0063,0.000000,0.009140,0.009140,0.009140,9.140431e+06,↑,5,16,2,19,0.000000,0.000000,0.000000,0.000000e+00,–,466,0,466,0,Discordant,35
ASPGLU2m,ASPGLU2m,Aspartate-glutamate transporter,"PAS_chr3_0434, PAS_chr4_0592",0.000000,0.000759,0.000759,0.000759,7.593755e+05,↑,294,0,145,0,2.486443,2.486443,2.486443,2.486443e+09,↑,6,15,1,20,↑ Consistent,35
GLUCYS,GLUCYS,gamma-glutamylcysteine synthetase,PAS_chr1-1_0184,0.000000,0.008336,0.008336,0.008336,8.336096e+06,↑,7,14,3,18,0.000000,0.000000,0.000000,0.000000e+00,–,466,0,466,0,Discordant,32
DABTDHR,DABTDHR,D-arabitol dehydrogenase (D-ribulose-forming),PAS_chr4_0433,0.000000,0.006523,0.006523,0.006523,6.522957e+06,↑,12,9,4,17,0.000000,0.000000,0.000000,0.000000e+00,–,466,0,466,0,Discordant,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
FAE4_18,FAE4_18,(2E)-octadecanoyl-CoA reductase,PAS_chr4_0780,0.007203,0.006483,-0.000720,0.000720,-1.000000e-01,↓,306,0,526,0,0.006483,-0.000720,0.000720,-1.000000e-01,↓,243,0,242,0,↓ Consistent,0
FAE4_20,FAE4_20,(2E)-Eicosanoyl-CoA reductase,PAS_chr4_0780,0.000058,0.000052,-0.000006,0.000006,-1.000000e-01,↓,632,0,469,0,0.000052,-0.000006,0.000006,-1.000000e-01,↓,331,0,295,0,↓ Consistent,0
FAE4_22,FAE4_22,(2E)-Docosanoyl-CoA reductase,PAS_chr4_0780,0.000058,0.000052,-0.000006,0.000006,-1.000000e-01,↓,632,0,469,0,0.000052,-0.000006,0.000006,-1.000000e-01,↓,331,0,295,0,↓ Consistent,0
FAE4_24,FAE4_24,(2E)-tetracosanoyl-CoA reductase,PAS_chr4_0780,0.000058,0.000052,-0.000006,0.000006,-1.000000e-01,↓,632,0,469,0,0.000052,-0.000006,0.000006,-1.000000e-01,↓,331,0,295,0,↓ Consistent,0
FAE4_26,FAE4_26,(2E)-hexacosanoyl-CoA reductase,PAS_chr4_0780,0.000044,0.000040,-0.000004,0.000004,-1.000000e-01,↓,644,0,469,0,0.000040,-0.000004,0.000004,-1.000000e-01,↓,347,0,259,0,↓ Consistent,0

In [21]:
# Export results to Excel
results_sorted.to_excel(
    "results/MOMA_pFBA_flux_comparison.xlsx",
    index=False
)

In [22]:
consistent_candidates.to_excel(
    "results/consistent_candidates.xlsx",
    index=False
)

print("Consistent candidates exported to results/consistent_candidates.xlsx")

Consistent candidates exported to results/consistent_candidates.xlsx

In [24]:
WT_RolProd_fluxes = pfba_WT_RolProd.fluxes.copy()

Reference_ROL = WT_RolProd_fluxes["Ex_rol"]
Reference_Growth = WT_RolProd_fluxes["Ex_biomass"]

print("Reference ROL production:", Reference_ROL)
print("Reference growth:", Reference_Growth)

ROL_exchange.bounds = (0.003, 1000)
# ============================================================
# 2. SELECT INITIAL CANDIDATE POPULATION
# ============================================================

# Only consistent candidates with at least 1 point
candidate_population = consistent_candidates[
    consistent_candidates["Total_Score"] >= 1
].copy()

print(
    "\nNumber of initial candidates:",
    len(candidate_population)
)


# ============================================================
# 3. TEST INTERVENTION LEVELS
# ============================================================

increase_levels = [0.10, 0.25, 0.50]
decrease_levels = [0.10, 0.25, 0.50]

screening_results = []


# ============================================================
# 4. TEST EACH CANDIDATE
# ============================================================

for reaction_id in candidate_population["Reaction"]:

    reaction = model.reactions.get_by_id(reaction_id)

    # Reference flux from WT pFBA ROL production state
    WT_flux = WT_RolProd_fluxes[reaction_id]

    # Determine intervention direction
    consensus = candidate_population.loc[
        candidate_population["Reaction"] == reaction_id,
        "Consensus"
    ].iloc[0]


    # --------------------------------------------------------
    # Determine intervention levels
    # --------------------------------------------------------

    if consensus == "↑ Consistent":

        intervention_levels = increase_levels
        direction = "Increase"

    elif consensus == "↓ Consistent":

        intervention_levels = decrease_levels
        direction = "Decrease"

    else:

        continue


    # --------------------------------------------------------
    # Skip reactions with essentially zero reference flux
    # --------------------------------------------------------

    if abs(WT_flux) < 1e-9:

        continue


    # ========================================================
    # TEST EACH INTERVENTION
    # ========================================================

    for level in intervention_levels:

        # Save original bounds
        original_bounds = reaction.bounds


        try:

            # ------------------------------------------------
            # Calculate target flux
            # ------------------------------------------------

            if direction == "Increase":

                target_flux = WT_flux * (1 + level)

            else:

                target_flux = WT_flux * (1 - level)


            # ------------------------------------------------
            # Apply intervention
            # ------------------------------------------------

            # Positive reference flux
            if WT_flux > 0:

                if direction == "Increase":

                    reaction.lower_bound = target_flux

                else:

                    reaction.upper_bound = target_flux


            # Negative reference flux
            elif WT_flux < 0:

                if direction == "Increase":

                    reaction.upper_bound = target_flux

                else:

                    reaction.lower_bound = target_flux


            # ------------------------------------------------
            # MOMA
            # ------------------------------------------------

            moma_result = cobra.flux_analysis.moma(
                model,
                pfba_WT_RolProd,
                0
            )


            # ------------------------------------------------
            # Check feasibility
            # ------------------------------------------------

            feasible = (
                moma_result.status == "optimal"
            )


            if feasible:

                growth = moma_result.fluxes["Ex_biomass"]
                ROL = moma_result.fluxes["Ex_rol"]

                positive_growth = (
                    growth > 1e-9
                )

                delta_ROL = (
                    ROL - Reference_ROL
                )

                relative_ROL_change = (
                    delta_ROL /
                    abs(Reference_ROL)
                    if abs(Reference_ROL) > 1e-9
                    else None
                )

                beneficial = (
                    feasible
                    and positive_growth
                    and ROL > Reference_ROL + 1e-9
                )

            else:

                growth = None
                ROL = None
                positive_growth = False
                delta_ROL = None
                relative_ROL_change = None
                beneficial = False


            # ------------------------------------------------
            # Store result
            # ------------------------------------------------

            screening_results.append({

                "Reaction": reaction_id,
                "Name": reaction.name,
                "Direction": direction,

                "WT_RolProd_Flux": WT_flux,

                "Intervention": (
                    f"{'+' if direction == 'Increase' else '-'}"
                    f"{int(level * 100)}%"
                ),

                "Intervention_Flux": target_flux,

                "Growth": growth,

                "ROL": ROL,

                "Delta_ROL": delta_ROL,

                "Relative_ROL_Change": (
                    relative_ROL_change
                ),

                "Feasible": feasible,

                "Positive_Growth": positive_growth,

                "Beneficial": beneficial
            })


        except Exception:

            screening_results.append({

                "Reaction": reaction_id,
                "Name": reaction.name,
                "Direction": direction,

                "WT_RolProd_Flux": WT_flux,

                "Intervention": (
                    f"{'+' if direction == 'Increase' else '-'}"
                    f"{int(level * 100)}%"
                ),

                "Intervention_Flux": target_flux,

                "Growth": None,
                "ROL": None,
                "Delta_ROL": None,
                "Relative_ROL_Change": None,

                "Feasible": False,
                "Positive_Growth": False,

                "Beneficial": False
            })


        finally:

            # Restore original reaction bounds
            reaction.bounds = original_bounds


# ============================================================
# 5. CREATE RESULTS DATAFRAME
# ============================================================

screening_results = pd.DataFrame(
    screening_results
)


# ============================================================
# 6. SORT RESULTS
# ============================================================

screening_results = screening_results.sort_values(
    [
        "Beneficial",
        "Delta_ROL"
    ],
    ascending=[
        False,
        False
    ]
)


# ============================================================
# 7. DISPLAY ALL RESULTS
# ============================================================

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

display(screening_results)


# ============================================================
# 8. SELECT BENEFICIAL INTERVENTIONS
# ============================================================

beneficial_candidates = screening_results[
    screening_results["Beneficial"] == True
].copy()

print(
    "\nBeneficial interventions:",
    len(beneficial_candidates)
)

display(beneficial_candidates)

Reference ROL production: 0.003
Reference growth: 0.08043246717999901

Number of initial candidates: 26

,Reaction,Name,Direction,WT_RolProd_Flux,Intervention,Intervention_Flux,Growth,ROL,Delta_ROL,Relative_ROL_Change,Feasible,Positive_Growth,Beneficial
14,CYOR_u6m,ubiquinol-6 cytochrome c reductase,Decrease,4.473236,-50%,2.236618,0.007970,0.033038,0.030038,10.012555,True,True,True
13,CYOR_u6m,ubiquinol-6 cytochrome c reductase,Decrease,4.473236,-25%,3.354927,0.044097,0.017872,0.014872,4.957417,True,True,True
2,NADH2_u6cm,"NADH dehydrogenase, cytosolic/mitochondrial",Decrease,3.054474,-50%,1.527237,0.060573,0.013291,0.010291,3.430235,True,True,True
23,FALDH2,formaldehyde dehydrogenase,Decrease,1.016800,-50%,0.508400,0.066845,0.009209,0.006209,2.069536,True,True,True
26,FALGTHLs,formaldehyde glutathione ligase (spontaneous),Decrease,1.016800,-50%,0.508400,0.066845,0.009209,0.006209,2.069536,True,True,True
29,SFGTH,S-Formylglutathione hydralase,Decrease,1.016800,-50%,0.508400,0.066845,0.009209,0.006209,2.069535,True,True,True
12,CYOR_u6m,ubiquinol-6 cytochrome c reductase,Decrease,4.473236,-10%,4.025912,0.066181,0.008797,0.005797,1.932203,True,True,True
1,NADH2_u6cm,"NADH dehydrogenase, cytosolic/mitochondrial",Decrease,3.054474,-25%,2.290855,0.070787,0.008011,0.005011,1.670497,True,True,True
25,FALGTHLs,formaldehyde glutathione ligase (spontaneous),Decrease,1.016800,-25%,0.762600,0.072379,0.007373,0.004373,1.457764,True,True,True
28,SFGTH,S-Formylglutathione hydralase,Decrease,1.016800,-25%,0.762600,0.072379,0.007373,0.004373,1.457764,True,True,True
22,FALDH2,formaldehyde dehydrogenase,Decrease,1.016800,-25%,0.762600,0.072379,0.007373,0.004373,1.457763,True,True,True
34,FDH,formate dehydrogenase,Decrease,0.959394,-25%,0.719545,0.073807,0.006320,0.003320,1.106589,True,True,True
38,HEX1,hexokinase (D-glucose:ATP),Increase,0.417555,+50%,0.626332,0.075167,0.005850,0.002850,0.950074,True,True,True
24,FALGTHLs,formaldehyde glutathione ligase (spontaneous),Decrease,1.016800,-10%,0.915120,0.076166,0.005503,0.002503,0.834425,True,True,True
21,FALDH2,formaldehyde dehydrogenase,Decrease,1.016800,-10%,0.915120,0.076166,0.005503,0.002503,0.834422,True,True,True
27,SFGTH,S-Formylglutathione hydralase,Decrease,1.016800,-10%,0.915120,0.076166,0.005503,0.002503,0.834400,True,True,True
0,NADH2_u6cm,"NADH dehydrogenase, cytosolic/mitochondrial",Decrease,3.054474,-10%,2.749027,0.076712,0.004900,0.001900,0.633206,True,True,True
32,PC,pyruvate carboxylase,Increase,0.247106,+50%,0.370660,0.076339,0.004849,0.001849,0.616196,True,True,True
37,HEX1,hexokinase (D-glucose:ATP),Increase,0.417555,+25%,0.521943,0.077805,0.004422,0.001422,0.474022,True,True,True
33,FDH,formate dehydrogenase,Decrease,0.959394,-10%,0.863454,0.077891,0.004273,0.001273,0.424333,True,True,True
20,DHAK,Dihydroxyacetone kinase,Increase,0.223200,+50%,0.334800,0.078157,0.004076,0.001076,0.358765,True,True,True
31,PC,pyruvate carboxylase,Increase,0.247106,+25%,0.308883,0.078385,0.003925,0.000925,0.308454,True,True,True
8,MDHm,"malate dehydrogenase, mitochondrial",Increase,0.268725,+50%,0.403088,0.076954,0.003916,0.000916,0.305354,True,True,True
17,GLNS,glutamine synthetase,Increase,0.117710,+50%,0.176565,0.078715,0.003862,0.000862,0.287340,True,True,True
36,HEX1,hexokinase (D-glucose:ATP),Increase,0.417555,+10%,0.459310,0.079384,0.003567,0.000567,0.188981,True,True,True
19,DHAK,Dihydroxyacetone kinase,Increase,0.223200,+25%,0.279000,0.079300,0.003535,0.000535,0.178305,True,True,True
7,MDHm,"malate dehydrogenase, mitochondrial",Increase,0.268725,+25%,0.335906,0.078793,0.003434,0.000434,0.144634,True,True,True
16,GLNS,glutamine synthetase,Increase,0.117710,+25%,0.147138,0.079605,0.003415,0.000415,0.138374,True,True,True
30,PC,pyruvate carboxylase,Increase,0.247106,+10%,0.271817,0.079613,0.003371,0.000371,0.123682,True,True,True
18,DHAK,Dihydroxyacetone kinase,Increase,0.223200,+10%,0.245520,0.079980,0.003214,0.000214,0.071213,True,True,True
6,MDHm,"malate dehydrogenase, mitochondrial",Increase,0.268725,+10%,0.295598,0.079818,0.003175,0.000175,0.058287,True,True,True
15,GLNS,glutamine synthetase,Increase,0.117710,+10%,0.129481,0.080102,0.003166,0.000166,0.055277,True,True,True
5,ASPTAm,aspartate transaminase,Decrease,0.028557,-50%,0.014279,0.080171,0.003118,0.000118,0.039191,True,True,True
4,ASPTAm,aspartate transaminase,Decrease,0.028557,-25%,0.021418,0.080302,0.003058,0.000058,0.019475,True,True,True
11,NDPK1,nucleoside-diphosphate kinase (ATP:GDP),Increase,0.011189,+50%,0.016783,0.080320,0.003055,0.000055,0.018268,True,True,True
41,CYTK1,cytidylate kinase (CMP),Increase,-0.002908,+50%,-0.004363,0.080341,0.003046,0.000046,0.015425,True,True,True
10,NDPK1,nucleoside-diphosphate kinase (ATP:GDP),Increase,0.011189,+25%,0.013986,0.080377,0.003027,0.000027,0.009048,True,True,True
40,CYTK1,cytidylate kinase (CMP),Increase,-0.002908,+25%,-0.003636,0.080386,0.003023,0.000023,0.007790,True,True,True
3,ASPTAm,aspartate transaminase,Decrease,0.028557,-10%,0.025701,0.080381,0.003023,0.000023,0.007644,True,True,True
9,NDPK1,nucleoside-diphosphate kinase (ATP:GDP),Increase,0.011189,+10%,0.012308,0.080411,0.003011,0.000011,0.003510,True,True,True
39,CYTK1,cytidylate kinase (CMP),Increase,-0.002908,+10%,-0.003199,0.080414,0.003009,0.000009,0.003034,True,True,True
35,FDH,formate dehydrogenase,Decrease,0.959394,-50%,0.479697,NaN,NaN,NaN,NaN,False,False,False

Beneficial interventions: 41

,Reaction,Name,Direction,WT_RolProd_Flux,Intervention,Intervention_Flux,Growth,ROL,Delta_ROL,Relative_ROL_Change,Feasible,Positive_Growth,Beneficial
14,CYOR_u6m,ubiquinol-6 cytochrome c reductase,Decrease,4.473236,-50%,2.236618,0.007970,0.033038,0.030038,10.012555,True,True,True
13,CYOR_u6m,ubiquinol-6 cytochrome c reductase,Decrease,4.473236,-25%,3.354927,0.044097,0.017872,0.014872,4.957417,True,True,True
2,NADH2_u6cm,"NADH dehydrogenase, cytosolic/mitochondrial",Decrease,3.054474,-50%,1.527237,0.060573,0.013291,0.010291,3.430235,True,True,True
23,FALDH2,formaldehyde dehydrogenase,Decrease,1.016800,-50%,0.508400,0.066845,0.009209,0.006209,2.069536,True,True,True
26,FALGTHLs,formaldehyde glutathione ligase (spontaneous),Decrease,1.016800,-50%,0.508400,0.066845,0.009209,0.006209,2.069536,True,True,True
29,SFGTH,S-Formylglutathione hydralase,Decrease,1.016800,-50%,0.508400,0.066845,0.009209,0.006209,2.069535,True,True,True
12,CYOR_u6m,ubiquinol-6 cytochrome c reductase,Decrease,4.473236,-10%,4.025912,0.066181,0.008797,0.005797,1.932203,True,True,True
1,NADH2_u6cm,"NADH dehydrogenase, cytosolic/mitochondrial",Decrease,3.054474,-25%,2.290855,0.070787,0.008011,0.005011,1.670497,True,True,True
25,FALGTHLs,formaldehyde glutathione ligase (spontaneous),Decrease,1.016800,-25%,0.762600,0.072379,0.007373,0.004373,1.457764,True,True,True
28,SFGTH,S-Formylglutathione hydralase,Decrease,1.016800,-25%,0.762600,0.072379,0.007373,0.004373,1.457764,True,True,True
22,FALDH2,formaldehyde dehydrogenase,Decrease,1.016800,-25%,0.762600,0.072379,0.007373,0.004373,1.457763,True,True,True
34,FDH,formate dehydrogenase,Decrease,0.959394,-25%,0.719545,0.073807,0.006320,0.003320,1.106589,True,True,True
38,HEX1,hexokinase (D-glucose:ATP),Increase,0.417555,+50%,0.626332,0.075167,0.005850,0.002850,0.950074,True,True,True
24,FALGTHLs,formaldehyde glutathione ligase (spontaneous),Decrease,1.016800,-10%,0.915120,0.076166,0.005503,0.002503,0.834425,True,True,True
21,FALDH2,formaldehyde dehydrogenase,Decrease,1.016800,-10%,0.915120,0.076166,0.005503,0.002503,0.834422,True,True,True
27,SFGTH,S-Formylglutathione hydralase,Decrease,1.016800,-10%,0.915120,0.076166,0.005503,0.002503,0.834400,True,True,True
0,NADH2_u6cm,"NADH dehydrogenase, cytosolic/mitochondrial",Decrease,3.054474,-10%,2.749027,0.076712,0.004900,0.001900,0.633206,True,True,True
32,PC,pyruvate carboxylase,Increase,0.247106,+50%,0.370660,0.076339,0.004849,0.001849,0.616196,True,True,True
37,HEX1,hexokinase (D-glucose:ATP),Increase,0.417555,+25%,0.521943,0.077805,0.004422,0.001422,0.474022,True,True,True
33,FDH,formate dehydrogenase,Decrease,0.959394,-10%,0.863454,0.077891,0.004273,0.001273,0.424333,True,True,True
20,DHAK,Dihydroxyacetone kinase,Increase,0.223200,+50%,0.334800,0.078157,0.004076,0.001076,0.358765,True,True,True
31,PC,pyruvate carboxylase,Increase,0.247106,+25%,0.308883,0.078385,0.003925,0.000925,0.308454,True,True,True
8,MDHm,"malate dehydrogenase, mitochondrial",Increase,0.268725,+50%,0.403088,0.076954,0.003916,0.000916,0.305354,True,True,True
17,GLNS,glutamine synthetase,Increase,0.117710,+50%,0.176565,0.078715,0.003862,0.000862,0.287340,True,True,True
36,HEX1,hexokinase (D-glucose:ATP),Increase,0.417555,+10%,0.459310,0.079384,0.003567,0.000567,0.188981,True,True,True
19,DHAK,Dihydroxyacetone kinase,Increase,0.223200,+25%,0.279000,0.079300,0.003535,0.000535,0.178305,True,True,True
7,MDHm,"malate dehydrogenase, mitochondrial",Increase,0.268725,+25%,0.335906,0.078793,0.003434,0.000434,0.144634,True,True,True
16,GLNS,glutamine synthetase,Increase,0.117710,+25%,0.147138,0.079605,0.003415,0.000415,0.138374,True,True,True
30,PC,pyruvate carboxylase,Increase,0.247106,+10%,0.271817,0.079613,0.003371,0.000371,0.123682,True,True,True
18,DHAK,Dihydroxyacetone kinase,Increase,0.223200,+10%,0.245520,0.079980,0.003214,0.000214,0.071213,True,True,True
6,MDHm,"malate dehydrogenase, mitochondrial",Increase,0.268725,+10%,0.295598,0.079818,0.003175,0.000175,0.058287,True,True,True
15,GLNS,glutamine synthetase,Increase,0.117710,+10%,0.129481,0.080102,0.003166,0.000166,0.055277,True,True,True
5,ASPTAm,aspartate transaminase,Decrease,0.028557,-50%,0.014279,0.080171,0.003118,0.000118,0.039191,True,True,True
4,ASPTAm,aspartate transaminase,Decrease,0.028557,-25%,0.021418,0.080302,0.003058,0.000058,0.019475,True,True,True
11,NDPK1,nucleoside-diphosphate kinase (ATP:GDP),Increase,0.011189,+50%,0.016783,0.080320,0.003055,0.000055,0.018268,True,True,True
41,CYTK1,cytidylate kinase (CMP),Increase,-0.002908,+50%,-0.004363,0.080341,0.003046,0.000046,0.015425,True,True,True
10,NDPK1,nucleoside-diphosphate kinase (ATP:GDP),Increase,0.011189,+25%,0.013986,0.080377,0.003027,0.000027,0.009048,True,True,True
40,CYTK1,cytidylate kinase (CMP),Increase,-0.002908,+25%,-0.003636,0.080386,0.003023,0.000023,0.007790,True,True,True
3,ASPTAm,aspartate transaminase,Decrease,0.028557,-10%,0.025701,0.080381,0.003023,0.000023,0.007644,True,True,True
9,NDPK1,nucleoside-diphosphate kinase (ATP:GDP),Increase,0.011189,+10%,0.012308,0.080411,0.003011,0.000011,0.003510,True,True,True
39,CYTK1,cytidylate kinase (CMP),Increase,-0.002908,+10%,-0.003199,0.080414,0.003009,0.000009,0.003034,True,True,True

In [28]:
# ============================================================
# 1. CALCULATE BPC
# ============================================================

screening_results["BPC"] = (
    screening_results["Growth"] *
    screening_results["ROL"]
)


# ============================================================
# 2. RANK ALL INTERVENTIONS BY BPC
# ============================================================

screening_results_BPC = screening_results.sort_values(
    "BPC",
    ascending=False
).copy()


# ============================================================
# 3. BEST INTERVENTION FOR EACH CANDIDATE
# ============================================================

best_BPC_per_candidate = (
    screening_results_BPC
    .dropna(subset=["BPC"])
    .loc[
        screening_results_BPC
        .dropna(subset=["BPC"])
        .groupby("Reaction")["BPC"]
        .idxmax()
    ]
    .sort_values("BPC", ascending=False)
    .reset_index(drop=True)
)


# ============================================================
# 4. DISPLAY RESULTS
# ============================================================

display(
    best_BPC_per_candidate[
        [
            "Reaction",
            "Name",
            "Direction",
            "WT_RolProd_Flux",
            "Intervention",
            "Intervention_Flux",
            "Growth",
            "ROL",
            "Delta_ROL",
            "Relative_ROL_Change",
            "BPC",
            "Beneficial"
        ]
    ]
)

# ============================================================
# 5. SAVE BEST INTERVENTION PER CANDIDATE TO EXCEL
# ============================================================

best_BPC_per_candidate[
    [
        "Reaction",
        "Name",
        "Direction",
        "WT_RolProd_Flux",
        "Intervention",
        "Intervention_Flux",
        "Growth",
        "ROL",
        "Delta_ROL",
        "Relative_ROL_Change",
        "BPC",
        "Beneficial"
    ]
].to_excel(
    "results/best_BPC_per_candidate.xlsx",
    index=False
)

print("Results saved to:")
print("results/best_BPC_per_candidate.xlsx")

,Reaction,Name,Direction,WT_RolProd_Flux,Intervention,Intervention_Flux,Growth,ROL,Delta_ROL,Relative_ROL_Change,BPC,Beneficial
0,NADH2_u6cm,"NADH dehydrogenase, cytosolic/mitochondrial",Decrease,3.054474,-50%,1.527237,0.060573,0.013291,0.010291,3.430235,0.000805,True
1,CYOR_u6m,ubiquinol-6 cytochrome c reductase,Decrease,4.473236,-25%,3.354927,0.044097,0.017872,0.014872,4.957417,0.000788,True
2,FALDH2,formaldehyde dehydrogenase,Decrease,1.016800,-50%,0.508400,0.066845,0.009209,0.006209,2.069536,0.000616,True
3,FALGTHLs,formaldehyde glutathione ligase (spontaneous),Decrease,1.016800,-50%,0.508400,0.066845,0.009209,0.006209,2.069536,0.000616,True
4,SFGTH,S-Formylglutathione hydralase,Decrease,1.016800,-50%,0.508400,0.066845,0.009209,0.006209,2.069535,0.000616,True
5,FDH,formate dehydrogenase,Decrease,0.959394,-25%,0.719545,0.073807,0.006320,0.003320,1.106589,0.000466,True
6,HEX1,hexokinase (D-glucose:ATP),Increase,0.417555,+50%,0.626332,0.075167,0.005850,0.002850,0.950074,0.000440,True
7,PC,pyruvate carboxylase,Increase,0.247106,+50%,0.370660,0.076339,0.004849,0.001849,0.616196,0.000370,True
8,DHAK,Dihydroxyacetone kinase,Increase,0.223200,+50%,0.334800,0.078157,0.004076,0.001076,0.358765,0.000319,True
9,GLNS,glutamine synthetase,Increase,0.117710,+50%,0.176565,0.078715,0.003862,0.000862,0.287340,0.000304,True
10,MDHm,"malate dehydrogenase, mitochondrial",Increase,0.268725,+50%,0.403088,0.076954,0.003916,0.000916,0.305354,0.000301,True
11,ASPTAm,aspartate transaminase,Decrease,0.028557,-50%,0.014279,0.080171,0.003118,0.000118,0.039191,0.000250,True
12,NDPK1,nucleoside-diphosphate kinase (ATP:GDP),Increase,0.011189,+50%,0.016783,0.080320,0.003055,0.000055,0.018268,0.000245,True
13,CYTK1,cytidylate kinase (CMP),Increase,-0.002908,+50%,-0.004363,0.080341,0.003046,0.000046,0.015425,0.000245,True

Results saved to:
results/best_BPC_per_candidate.xlsx

In [26]:
import random
from itertools import combinations

# ============================================================
# 1. REFERENCE STATE
# ============================================================

WT_RolProd_fluxes = pfba_WT_RolProd.fluxes.copy()

Reference_ROL = WT_RolProd_fluxes["Ex_rol"]
Reference_Growth = WT_RolProd_fluxes["Ex_biomass"]


# Make sure growth is NOT fixed to 0.9 WT
Growth = model.reactions.get_by_id("Ex_biomass")
Growth.bounds = (0, 1000)

ROL_exchange = model.reactions.get_by_id("Ex_rol")
ROL_exchange.bounds = (0, 1000)


# ============================================================
# 2. STARTING POPULATION
# ============================================================

# best_BPC_per_candidate contains the best intervention
# found for each individual candidate

population = best_BPC_per_candidate.copy()

print("Initial population:", len(population))


# ============================================================
# 3. FUNCTION TO APPLY AN INTERVENTION
# ============================================================

def set_intervention(reaction, WT_flux, direction, level):

    if WT_flux > 0:

        target_flux = (
            WT_flux * (1 + level)
            if direction == "Increase"
            else WT_flux * (1 - level)
        )

        if direction == "Increase":
            reaction.lower_bound = target_flux
        else:
            reaction.upper_bound = target_flux

    elif WT_flux < 0:

        target_flux = (
            WT_flux * (1 + level)
            if direction == "Increase"
            else WT_flux * (1 - level)
        )

        if direction == "Increase":
            reaction.upper_bound = target_flux
        else:
            reaction.lower_bound = target_flux

    else:
        target_flux = None

    return target_flux


# ============================================================
# 4. FUNCTION TO TEST ONE COMBINATION
# ============================================================

def test_combination(candidate_1, candidate_2):

    reaction_1_id = candidate_1["Reaction"]
    reaction_2_id = candidate_2["Reaction"]

    reaction_1 = model.reactions.get_by_id(reaction_1_id)
    reaction_2 = model.reactions.get_by_id(reaction_2_id)

    # Reference fluxes
    WT_flux_1 = WT_RolProd_fluxes[reaction_1_id]
    WT_flux_2 = WT_RolProd_fluxes[reaction_2_id]

    direction_1 = candidate_1["Direction"]
    direction_2 = candidate_2["Direction"]

    # Convert intervention string into decimal
    level_1 = abs(float(
        candidate_1["Intervention"]
        .replace("+", "")
        .replace("-", "")
        .replace("%", "")
    )) / 100

    level_2 = abs(float(
        candidate_2["Intervention"]
        .replace("+", "")
        .replace("-", "")
        .replace("%", "")
    )) / 100

    original_bounds_1 = reaction_1.bounds
    original_bounds_2 = reaction_2.bounds

    try:

        # ----------------------------------------------------
        # Apply BOTH interventions
        # ----------------------------------------------------

        target_1 = set_intervention(
            reaction_1,
            WT_flux_1,
            direction_1,
            level_1
        )

        target_2 = set_intervention(
            reaction_2,
            WT_flux_2,
            direction_2,
            level_2
        )


        # ----------------------------------------------------
        # MOMA
        # ----------------------------------------------------

        moma_result = cobra.flux_analysis.moma(
            model,
            pfba_WT_RolProd,
            0
        )


        feasible = (
            moma_result.status == "optimal"
        )


        if feasible:

            growth = moma_result.fluxes["Ex_biomass"]
            ROL = moma_result.fluxes["Ex_rol"]

            positive_growth = (
                growth > 1e-9
            )

            BPC = (
                growth * ROL
            )

            delta_ROL = (
                ROL - Reference_ROL
            )

            relative_ROL_change = (
                delta_ROL / abs(Reference_ROL)
                if abs(Reference_ROL) > 1e-9
                else None
            )

            beneficial = (
                positive_growth
                and ROL > Reference_ROL + 1e-9
            )

        else:

            growth = None
            ROL = None
            BPC = None
            delta_ROL = None
            relative_ROL_change = None
            positive_growth = False
            beneficial = False


        return {

            "Candidate_1": reaction_1_id,
            "Name_1": candidate_1["Name"],
            "Intervention_1": candidate_1["Intervention"],
            "Flux_1": target_1,

            "Candidate_2": reaction_2_id,
            "Name_2": candidate_2["Name"],
            "Intervention_2": candidate_2["Intervention"],
            "Flux_2": target_2,

            "Growth": growth,
            "ROL": ROL,
            "BPC": BPC,

            "Delta_ROL": delta_ROL,
            "Relative_ROL_Change": relative_ROL_change,

            "Feasible": feasible,
            "Positive_Growth": positive_growth,
            "Beneficial": beneficial
        }


    except Exception:

        return {

            "Candidate_1": reaction_1_id,
            "Name_1": candidate_1["Name"],
            "Intervention_1": candidate_1["Intervention"],
            "Flux_1": target_1 if "target_1" in locals() else None,

            "Candidate_2": reaction_2_id,
            "Name_2": candidate_2["Name"],
            "Intervention_2": candidate_2["Intervention"],
            "Flux_2": target_2 if "target_2" in locals() else None,

            "Growth": None,
            "ROL": None,
            "BPC": None,

            "Delta_ROL": None,
            "Relative_ROL_Change": None,

            "Feasible": False,
            "Positive_Growth": False,
            "Beneficial": False
        }


    finally:

        # ----------------------------------------------------
        # ALWAYS restore original bounds
        # ----------------------------------------------------

        reaction_1.bounds = original_bounds_1
        reaction_2.bounds = original_bounds_2

Initial population: 14

In [36]:
# ============================================================
# ITERATION 1
# ============================================================

N_COMBINATIONS = 20

# Generate all possible candidate pairs
all_pairs = list(
    combinations(
        population.index,
        2
    )
)

# Randomly select 20

if len(all_pairs) > N_COMBINATIONS:
    selected_pairs = random.sample(
        all_pairs,
        N_COMBINATIONS
    )
else:
    selected_pairs = all_pairs


# ============================================================
# TEST PAIRS
# ============================================================

generation_results = []

for idx_1, idx_2 in selected_pairs:

    candidate_1 = population.loc[idx_1]
    candidate_2 = population.loc[idx_2]

    result = test_combination(
        candidate_1,
        candidate_2
    )

    generation_results.append(result)


generation_results = pd.DataFrame(
    generation_results
)


# ============================================================
# RANK BY BPC
# ============================================================

generation_results = generation_results.sort_values(
    "BPC",
    ascending=False
).reset_index(drop=True)


# ============================================================
# DISPLAY
# ============================================================

display(
    generation_results[
        [
            "Candidate_1",
            "Intervention_1",
            "Candidate_2",
            "Intervention_2",
            "Growth",
            "ROL",
            "BPC",
            "Delta_ROL",
            "Beneficial"
        ]
    ]
)

,Candidate_1,Intervention_1,Candidate_2,Intervention_2,Growth,ROL,BPC,Delta_ROL,Beneficial
0,CYOR_u6m,-25%,SFGTH,-50%,0.040629,0.020462,0.000831,0.017462,True
1,CYOR_u6m,-25%,MDHm,+50%,0.044097,0.017872,0.000788,0.014872,True
2,CYOR_u6m,-25%,CYTK1,+50%,0.044194,0.017821,0.000788,0.014821,True
3,FALDH2,-50%,MDHm,+50%,0.065766,0.009487,0.000624,0.006487,True
4,SFGTH,-50%,MDHm,+50%,0.065766,0.009487,0.000624,0.006487,True
5,SFGTH,-50%,DHAK,+50%,0.066845,0.009209,0.000616,0.006209,True
6,FALDH2,-50%,FDH,-25%,0.066845,0.009209,0.000616,0.006209,True
7,SFGTH,-50%,CYTK1,+50%,0.066879,0.009192,0.000615,0.006192,True
8,FALGTHLs,-50%,CYTK1,+50%,0.066879,0.009192,0.000615,0.006192,True
9,FDH,-25%,PC,+50%,0.070918,0.007750,0.000550,0.004750,True
10,FDH,-25%,NDPK1,+50%,0.073796,0.006326,0.000467,0.003326,True
11,PC,+50%,GLNS,+50%,0.075392,0.005381,0.000406,0.002381,True
12,PC,+50%,MDHm,+50%,0.073868,0.005310,0.000392,0.002310,True
13,DHAK,+50%,GLNS,+50%,0.076545,0.004896,0.000375,0.001896,True
14,PC,+50%,NDPK1,+50%,0.076297,0.004869,0.000371,0.001869,True
15,PC,+50%,CYTK1,+50%,0.076357,0.004840,0.000370,0.001840,True
16,DHAK,+50%,MDHm,+50%,0.075533,0.004578,0.000346,0.001578,True
17,DHAK,+50%,NDPK1,+50%,0.078094,0.004107,0.000321,0.001107,True
18,GLNS,+50%,CYTK1,+50%,0.078715,0.003862,0.000304,0.000862,True
19,ASPTAm,-50%,NDPK1,+50%,0.080128,0.003139,0.000251,0.000139,True

In [37]:
top_combinations = generation_results[
    generation_results["Beneficial"] == True
].head(5).copy()

display(top_combinations)

,Candidate_1,Name_1,Intervention_1,Flux_1,Candidate_2,Name_2,Intervention_2,Flux_2,Growth,ROL,BPC,Delta_ROL,Relative_ROL_Change,Feasible,Positive_Growth,Beneficial
0,CYOR_u6m,ubiquinol-6 cytochrome c reductase,-25%,3.354927,SFGTH,S-Formylglutathione hydralase,-50%,0.508400,0.040629,0.020462,0.000831,0.017462,5.820672,True,True,True
1,CYOR_u6m,ubiquinol-6 cytochrome c reductase,-25%,3.354927,MDHm,"malate dehydrogenase, mitochondrial",+50%,0.403088,0.044097,0.017872,0.000788,0.014872,4.957406,True,True,True
2,CYOR_u6m,ubiquinol-6 cytochrome c reductase,-25%,3.354927,CYTK1,cytidylate kinase (CMP),+50%,-0.004363,0.044194,0.017821,0.000788,0.014821,4.940390,True,True,True
3,FALDH2,formaldehyde dehydrogenase,-50%,0.508400,MDHm,"malate dehydrogenase, mitochondrial",+50%,0.403088,0.065766,0.009487,0.000624,0.006487,2.162233,True,True,True
4,SFGTH,S-Formylglutathione hydralase,-50%,0.508400,MDHm,"malate dehydrogenase, mitochondrial",+50%,0.403088,0.065766,0.009487,0.000624,0.006487,2.162226,True,True,True

In [38]:
# ============================================================
# SAVE SECOND-GENERATION DUO MUTANTS
# ============================================================

#For each iteration the results will have to be saved

top_combinations.to_excel(
    "results/second_generation_duo_mutants_iterationX.xlsx",
    index=False
)

print("Second-generation duo mutants saved to:")
print("results/second_generation_duo_mutants.xlsx")

Second-generation duo mutants saved to:
results/second_generation_duo_mutants.xlsx

In [40]:
# ============================================================
# THIRD GENERATION — SELECT THE TWO BEST DUOS
# ============================================================

best_duos = (
    generation_results
    [generation_results["Beneficial"] == True]
    .head(2)
    .copy()
)

display(
    best_duos[
        [
            "Candidate_1",
            "Intervention_1",
            "Candidate_2",
            "Intervention_2",
            "Growth",
            "ROL",
            "BPC"
        ]
    ]
)

,Candidate_1,Intervention_1,Candidate_2,Intervention_2,Growth,ROL,BPC
0,CYOR_u6m,-25%,SFGTH,-50%,0.040629,0.020462,0.000831
1,CYOR_u6m,-25%,MDHm,+50%,0.044097,0.017872,0.000788

In [43]:
# ============================================================
# THIRD GENERATION — TRIOS
# ============================================================

N_EXTRA_CANDIDATES = 10

third_generation_results = []


# ============================================================
# LOOP THROUGH THE TWO BEST DUOS
# ============================================================

for _, duo in best_duos.iterrows():

    candidate_1_id = duo["Candidate_1"]
    candidate_2_id = duo["Candidate_2"]

    # Candidates already present in the duo
    existing_candidates = {
        candidate_1_id,
        candidate_2_id
    }

    # Remove both candidates from the pool
    available_candidates = population[
        ~population["Reaction"].isin(
            existing_candidates
        )
    ]

    # Randomly select 10 additional candidates
    n_select = min(
        N_EXTRA_CANDIDATES,
        len(available_candidates)
    )

    extra_candidates = available_candidates.sample(
        n=n_select
    )


    # ========================================================
    # TEST EACH TRIO
    # ========================================================

    for _, candidate_3 in extra_candidates.iterrows():

        reaction_1 = model.reactions.get_by_id(
            candidate_1_id
        )

        reaction_2 = model.reactions.get_by_id(
            candidate_2_id
        )

        reaction_3 = model.reactions.get_by_id(
            candidate_3["Reaction"]
        )


        # ----------------------------------------------------
        # Save original bounds
        # ----------------------------------------------------

        original_bounds_1 = reaction_1.bounds
        original_bounds_2 = reaction_2.bounds
        original_bounds_3 = reaction_3.bounds


        try:

            # ------------------------------------------------
            # Apply first intervention
            # ------------------------------------------------

            WT_flux_1 = WT_RolProd_fluxes[
                candidate_1_id
            ]

            level_1 = abs(float(
                duo["Intervention_1"]
                .replace("+", "")
                .replace("-", "")
                .replace("%", "")
            )) / 100

            direction_1 = (
                "Increase"
                if duo["Intervention_1"].startswith("+")
                else "Decrease"
            )

            target_1 = set_intervention(
                reaction_1,
                WT_flux_1,
                direction_1,
                level_1
            )


            # ------------------------------------------------
            # Apply second intervention
            # ------------------------------------------------

            WT_flux_2 = WT_RolProd_fluxes[
                candidate_2_id
            ]

            level_2 = abs(float(
                duo["Intervention_2"]
                .replace("+", "")
                .replace("-", "")
                .replace("%", "")
            )) / 100

            direction_2 = (
                "Increase"
                if duo["Intervention_2"].startswith("+")
                else "Decrease"
            )

            target_2 = set_intervention(
                reaction_2,
                WT_flux_2,
                direction_2,
                level_2
            )


            # ------------------------------------------------
            # Apply third intervention
            # ------------------------------------------------

            WT_flux_3 = WT_RolProd_fluxes[
                candidate_3["Reaction"]
            ]

            level_3 = abs(float(
                candidate_3["Intervention"]
                .replace("+", "")
                .replace("-", "")
                .replace("%", "")
            )) / 100

            direction_3 = candidate_3["Direction"]

            target_3 = set_intervention(
                reaction_3,
                WT_flux_3,
                direction_3,
                level_3
            )


            # =================================================
            # MOMA
            # =================================================

            moma_result = cobra.flux_analysis.moma(
                model,
                pfba_WT_RolProd,
                0
            )


            feasible = (
                moma_result.status == "optimal"
            )


            if feasible:

                growth = moma_result.fluxes[
                    "Ex_biomass"
                ]

                ROL = moma_result.fluxes[
                    "Ex_rol"
                ]

                BPC = growth * ROL

                delta_ROL = (
                    ROL - Reference_ROL
                )

                relative_ROL_change = (
                    delta_ROL /
                    abs(Reference_ROL)
                    if abs(Reference_ROL) > 1e-9
                    else None
                )

                positive_growth = (
                    growth > 1e-9
                )

                beneficial = (
                    positive_growth
                    and ROL > Reference_ROL + 1e-9
                )

            else:

                growth = None
                ROL = None
                BPC = None
                delta_ROL = None
                relative_ROL_change = None
                positive_growth = False
                beneficial = False


            # =================================================
            # STORE RESULT
            # =================================================

            third_generation_results.append({

                "Candidate_1": candidate_1_id,
                "Intervention_1": duo["Intervention_1"],
                "Flux_1": target_1,

                "Candidate_2": candidate_2_id,
                "Intervention_2": duo["Intervention_2"],
                "Flux_2": target_2,

                "Candidate_3": candidate_3["Reaction"],
                "Intervention_3": candidate_3["Intervention"],
                "Flux_3": target_3,

                "Growth": growth,
                "ROL": ROL,
                "BPC": BPC,

                "Delta_ROL": delta_ROL,
                "Relative_ROL_Change":
                    relative_ROL_change,

                "Feasible": feasible,
                "Positive_Growth":
                    positive_growth,
                "Beneficial": beneficial
            })


        except Exception:

            third_generation_results.append({

                "Candidate_1": candidate_1_id,
                "Intervention_1": duo["Intervention_1"],
                "Flux_1": None,

                "Candidate_2": candidate_2_id,
                "Intervention_2": duo["Intervention_2"],
                "Flux_2": None,

                "Candidate_3": candidate_3["Reaction"],
                "Intervention_3": candidate_3["Intervention"],
                "Flux_3": None,

                "Growth": None,
                "ROL": None,
                "BPC": None,

                "Delta_ROL": None,
                "Relative_ROL_Change": None,

                "Feasible": False,
                "Positive_Growth": False,
                "Beneficial": False
            })


        finally:

            # ------------------------------------------------
            # Restore all original bounds
            # ------------------------------------------------

            reaction_1.bounds = original_bounds_1
            reaction_2.bounds = original_bounds_2
            reaction_3.bounds = original_bounds_3


# ============================================================
# CREATE DATAFRAME
# ============================================================

third_generation_results = pd.DataFrame(
    third_generation_results
)


# ============================================================
# RANK BY BPC
# ============================================================

third_generation_results = (
    third_generation_results
    .sort_values(
        "BPC",
        ascending=False
    )
    .reset_index(drop=True)
)


# ============================================================
# DISPLAY RESULTS
# ============================================================

display(
    third_generation_results[
        [
            "Candidate_1",
            "Intervention_1",
            "Candidate_2",
            "Intervention_2",
            "Candidate_3",
            "Intervention_3",
            "Growth",
            "ROL",
            "BPC",
            "Delta_ROL",
            "Beneficial"
        ]
    ]
)

,Candidate_1,Intervention_1,Candidate_2,Intervention_2,Candidate_3,Intervention_3,Growth,ROL,BPC,Delta_ROL,Beneficial
0,CYOR_u6m,-25%,SFGTH,-50%,NADH2_u6cm,-50%,0.039615,0.024874,0.000985,0.021874,True
1,CYOR_u6m,-25%,MDHm,+50%,NADH2_u6cm,-50%,0.039594,0.024089,0.000954,0.021089,True
2,CYOR_u6m,-25%,SFGTH,-50%,HEX1,+50%,0.039087,0.021324,0.000833,0.018324,True
3,CYOR_u6m,-25%,SFGTH,-50%,PC,+50%,0.040387,0.020602,0.000832,0.017602,True
4,CYOR_u6m,-25%,SFGTH,-50%,GLNS,+50%,0.040089,0.020753,0.000832,0.017753,True
5,CYOR_u6m,-25%,SFGTH,-50%,ASPTAm,-50%,0.040629,0.020462,0.000831,0.017462,True
6,CYOR_u6m,-25%,MDHm,+50%,FALDH2,-50%,0.040629,0.020462,0.000831,0.017462,True
7,CYOR_u6m,-25%,SFGTH,-50%,MDHm,+50%,0.040629,0.020462,0.000831,0.017462,True
8,CYOR_u6m,-25%,SFGTH,-50%,FALGTHLs,-50%,0.040629,0.020462,0.000831,0.017462,True
9,CYOR_u6m,-25%,MDHm,+50%,FALGTHLs,-50%,0.040629,0.020462,0.000831,0.017462,True
10,CYOR_u6m,-25%,SFGTH,-50%,DHAK,+50%,0.040629,0.020462,0.000831,0.017462,True
11,CYOR_u6m,-25%,SFGTH,-50%,FALDH2,-50%,0.040629,0.020462,0.000831,0.017462,True
12,CYOR_u6m,-25%,SFGTH,-50%,CYTK1,+50%,0.040717,0.020417,0.000831,0.017417,True
13,CYOR_u6m,-25%,MDHm,+50%,FDH,-25%,0.042232,0.019049,0.000804,0.016049,True
14,CYOR_u6m,-25%,MDHm,+50%,HEX1,+50%,0.041996,0.019095,0.000802,0.016095,True
15,CYOR_u6m,-25%,MDHm,+50%,GLNS,+50%,0.043691,0.018142,0.000793,0.015142,True
16,CYOR_u6m,-25%,MDHm,+50%,ASPTAm,-50%,0.044097,0.017872,0.000788,0.014872,True
17,CYOR_u6m,-25%,MDHm,+50%,NDPK1,+50%,0.044096,0.017872,0.000788,0.014872,True
18,CYOR_u6m,-25%,MDHm,+50%,PC,+50%,0.044097,0.017872,0.000788,0.014872,True
19,CYOR_u6m,-25%,MDHm,+50%,DHAK,+50%,0.043953,0.017892,0.000786,0.014892,True

In [44]:
# ============================================================
# SAVE THIRD-GENERATION TRIOS
# ============================================================

third_generation_results.to_excel(
    "results/third_generation_trios.xlsx",
    index=False
)

print("Third-generation trio results saved to:")
print("results/third_generation_trios.xlsx")

Third-generation trio results saved to:
results/third_generation_trios.xlsx

In [47]:
# ============================================================
# FOURTH GENERATION — 4-WAY INTERVENTIONS
# ============================================================

N_EXTRA_CANDIDATES = 10

# ============================================================
# 1. SELECT THE TWO BEST TRIOS
# ============================================================

best_trios = (
    third_generation_results[
        third_generation_results["Beneficial"] == True
    ]
    .sort_values("BPC", ascending=False)
    .head(2)
    .copy()
)

print("Selected third-generation trios:")

display(
    best_trios[
        [
            "Candidate_1",
            "Intervention_1",
            "Candidate_2",
            "Intervention_2",
            "Candidate_3",
            "Intervention_3",
            "Growth",
            "ROL",
            "BPC"
        ]
    ]
)


# ============================================================
# 2. TEST FOUR-WAY COMBINATIONS
# ============================================================

fourth_generation_results = []


for _, trio in best_trios.iterrows():

    candidate_1_id = trio["Candidate_1"]
    candidate_2_id = trio["Candidate_2"]
    candidate_3_id = trio["Candidate_3"]

    # Candidates already present in the trio
    existing_candidates = {
        candidate_1_id,
        candidate_2_id,
        candidate_3_id
    }

    # Remove them from the original candidate population
    available_candidates = population[
        ~population["Reaction"].isin(
            existing_candidates
        )
    ]

    # Randomly select 10 additional candidates
    n_select = min(
        N_EXTRA_CANDIDATES,
        len(available_candidates)
    )

    extra_candidates = available_candidates.sample(
        n=n_select
    )


    # ========================================================
    # 3. TEST EACH FOUR-WAY COMBINATION
    # ========================================================

    for _, candidate_4 in extra_candidates.iterrows():

        reaction_1 = model.reactions.get_by_id(
            candidate_1_id
        )

        reaction_2 = model.reactions.get_by_id(
            candidate_2_id
        )

        reaction_3 = model.reactions.get_by_id(
            candidate_3_id
        )

        reaction_4 = model.reactions.get_by_id(
            candidate_4["Reaction"]
        )


        # ----------------------------------------------------
        # Save original bounds
        # ----------------------------------------------------

        original_bounds_1 = reaction_1.bounds
        original_bounds_2 = reaction_2.bounds
        original_bounds_3 = reaction_3.bounds
        original_bounds_4 = reaction_4.bounds


        try:

            # =================================================
            # APPLY INTERVENTION 1
            # =================================================

            WT_flux_1 = WT_RolProd_fluxes[
                candidate_1_id
            ]

            level_1 = abs(float(
                trio["Intervention_1"]
                .replace("+", "")
                .replace("-", "")
                .replace("%", "")
            )) / 100

            direction_1 = (
                "Increase"
                if trio["Intervention_1"].startswith("+")
                else "Decrease"
            )

            target_1 = set_intervention(
                reaction_1,
                WT_flux_1,
                direction_1,
                level_1
            )


            # =================================================
            # APPLY INTERVENTION 2
            # =================================================

            WT_flux_2 = WT_RolProd_fluxes[
                candidate_2_id
            ]

            level_2 = abs(float(
                trio["Intervention_2"]
                .replace("+", "")
                .replace("-", "")
                .replace("%", "")
            )) / 100

            direction_2 = (
                "Increase"
                if trio["Intervention_2"].startswith("+")
                else "Decrease"
            )

            target_2 = set_intervention(
                reaction_2,
                WT_flux_2,
                direction_2,
                level_2
            )


            # =================================================
            # APPLY INTERVENTION 3
            # =================================================

            WT_flux_3 = WT_RolProd_fluxes[
                candidate_3_id
            ]

            level_3 = abs(float(
                trio["Intervention_3"]
                .replace("+", "")
                .replace("-", "")
                .replace("%", "")
            )) / 100

            direction_3 = (
                "Increase"
                if trio["Intervention_3"].startswith("+")
                else "Decrease"
            )

            target_3 = set_intervention(
                reaction_3,
                WT_flux_3,
                direction_3,
                level_3
            )


            # =================================================
            # APPLY INTERVENTION 4
            # =================================================

            WT_flux_4 = WT_RolProd_fluxes[
                candidate_4["Reaction"]
            ]

            level_4 = abs(float(
                candidate_4["Intervention"]
                .replace("+", "")
                .replace("-", "")
                .replace("%", "")
            )) / 100

            direction_4 = candidate_4["Direction"]

            target_4 = set_intervention(
                reaction_4,
                WT_flux_4,
                direction_4,
                level_4
            )


            # =================================================
            # MOMA
            # =================================================

            moma_result = cobra.flux_analysis.moma(
                model,
                pfba_WT_RolProd,
                0
            )


            feasible = (
                moma_result.status == "optimal"
            )


            # =================================================
            # RESULTS
            # =================================================

            if feasible:

                growth = moma_result.fluxes[
                    "Ex_biomass"
                ]

                ROL = moma_result.fluxes[
                    "Ex_rol"
                ]

                BPC = growth * ROL

                delta_ROL = (
                    ROL - Reference_ROL
                )

                relative_ROL_change = (
                    delta_ROL /
                    abs(Reference_ROL)
                    if abs(Reference_ROL) > 1e-9
                    else None
                )

                positive_growth = (
                    growth > 1e-9
                )

                beneficial = (
                    positive_growth
                    and ROL > Reference_ROL + 1e-9
                )

            else:

                growth = None
                ROL = None
                BPC = None
                delta_ROL = None
                relative_ROL_change = None
                positive_growth = False
                beneficial = False


            # =================================================
            # STORE RESULT
            # =================================================

            fourth_generation_results.append({

                "Candidate_1": candidate_1_id,
                "Intervention_1": trio["Intervention_1"],
                "Flux_1": target_1,

                "Candidate_2": candidate_2_id,
                "Intervention_2": trio["Intervention_2"],
                "Flux_2": target_2,

                "Candidate_3": candidate_3_id,
                "Intervention_3": trio["Intervention_3"],
                "Flux_3": target_3,

                "Candidate_4": candidate_4["Reaction"],
                "Intervention_4": candidate_4["Intervention"],
                "Flux_4": target_4,

                "Growth": growth,
                "ROL": ROL,
                "BPC": BPC,

                "Delta_ROL": delta_ROL,
                "Relative_ROL_Change":
                    relative_ROL_change,

                "Feasible": feasible,
                "Positive_Growth":
                    positive_growth,
                "Beneficial": beneficial
            })


        except Exception:

            fourth_generation_results.append({

                "Candidate_1": candidate_1_id,
                "Intervention_1": trio["Intervention_1"],
                "Flux_1": None,

                "Candidate_2": candidate_2_id,
                "Intervention_2": trio["Intervention_2"],
                "Flux_2": None,

                "Candidate_3": candidate_3_id,
                "Intervention_3": trio["Intervention_3"],
                "Flux_3": None,

                "Candidate_4": candidate_4["Reaction"],
                "Intervention_4": candidate_4["Intervention"],
                "Flux_4": None,

                "Growth": None,
                "ROL": None,
                "BPC": None,

                "Delta_ROL": None,
                "Relative_ROL_Change": None,

                "Feasible": False,
                "Positive_Growth": False,
                "Beneficial": False
            })


        finally:

            # Restore all original bounds
            reaction_1.bounds = original_bounds_1
            reaction_2.bounds = original_bounds_2
            reaction_3.bounds = original_bounds_3
            reaction_4.bounds = original_bounds_4


# ============================================================
# 5. CREATE DATAFRAME
# ============================================================

fourth_generation_results = pd.DataFrame(
    fourth_generation_results
)


# ============================================================
# 6. RANK BY BPC
# ============================================================

fourth_generation_results = (
    fourth_generation_results
    .sort_values(
        "BPC",
        ascending=False
    )
    .reset_index(drop=True)
)


# ============================================================
# 7. DISPLAY RESULTS
# ============================================================

display(
    fourth_generation_results[
        [
            "Candidate_1",
            "Intervention_1",
            "Candidate_2",
            "Intervention_2",
            "Candidate_3",
            "Intervention_3",
            "Candidate_4",
            "Intervention_4",
            "Growth",
            "ROL",
            "BPC",
            "Delta_ROL",
            "Beneficial"
        ]
    ]
)

Selected third-generation trios:

,Candidate_1,Intervention_1,Candidate_2,Intervention_2,Candidate_3,Intervention_3,Growth,ROL,BPC
0,CYOR_u6m,-25%,SFGTH,-50%,NADH2_u6cm,-50%,0.039615,0.024874,0.000985
1,CYOR_u6m,-25%,MDHm,+50%,NADH2_u6cm,-50%,0.039594,0.024089,0.000954

,Candidate_1,Intervention_1,Candidate_2,Intervention_2,Candidate_3,Intervention_3,Candidate_4,Intervention_4,Growth,ROL,BPC,Delta_ROL,Beneficial
0,CYOR_u6m,-25%,SFGTH,-50%,NADH2_u6cm,-50%,CYTK1,+50%,0.039661,0.024851,0.000986,0.021851,True
1,CYOR_u6m,-25%,SFGTH,-50%,NADH2_u6cm,-50%,DHAK,+50%,0.039615,0.024874,0.000985,0.021874,True
2,CYOR_u6m,-25%,MDHm,+50%,NADH2_u6cm,-50%,FALDH2,-50%,0.039615,0.024874,0.000985,0.021874,True
3,CYOR_u6m,-25%,SFGTH,-50%,NADH2_u6cm,-50%,NDPK1,+50%,0.039615,0.024874,0.000985,0.021874,True
4,CYOR_u6m,-25%,SFGTH,-50%,NADH2_u6cm,-50%,FDH,-25%,0.039615,0.024874,0.000985,0.021874,True
5,CYOR_u6m,-25%,SFGTH,-50%,NADH2_u6cm,-50%,MDHm,+50%,0.039615,0.024874,0.000985,0.021874,True
6,CYOR_u6m,-25%,MDHm,+50%,NADH2_u6cm,-50%,SFGTH,-50%,0.039615,0.024874,0.000985,0.021874,True
7,CYOR_u6m,-25%,SFGTH,-50%,NADH2_u6cm,-50%,GLNS,+50%,0.039615,0.024874,0.000985,0.021874,True
8,CYOR_u6m,-25%,SFGTH,-50%,NADH2_u6cm,-50%,FALDH2,-50%,0.039615,0.024874,0.000985,0.021874,True
9,CYOR_u6m,-25%,MDHm,+50%,NADH2_u6cm,-50%,FALGTHLs,-50%,0.039615,0.024874,0.000985,0.021874,True
10,CYOR_u6m,-25%,SFGTH,-50%,NADH2_u6cm,-50%,ASPTAm,-50%,0.039615,0.024874,0.000985,0.021874,True
11,CYOR_u6m,-25%,SFGTH,-50%,NADH2_u6cm,-50%,PC,+50%,0.039247,0.025085,0.000984,0.022085,True
12,CYOR_u6m,-25%,MDHm,+50%,NADH2_u6cm,-50%,FDH,-25%,0.039537,0.024169,0.000956,0.021169,True
13,CYOR_u6m,-25%,MDHm,+50%,NADH2_u6cm,-50%,CYTK1,+50%,0.039662,0.024054,0.000954,0.021054,True
14,CYOR_u6m,-25%,MDHm,+50%,NADH2_u6cm,-50%,PC,+50%,0.039594,0.024089,0.000954,0.021089,True
15,CYOR_u6m,-25%,MDHm,+50%,NADH2_u6cm,-50%,NDPK1,+50%,0.039594,0.024089,0.000954,0.021089,True
16,CYOR_u6m,-25%,MDHm,+50%,NADH2_u6cm,-50%,GLNS,+50%,0.039594,0.024089,0.000954,0.021089,True
17,CYOR_u6m,-25%,MDHm,+50%,NADH2_u6cm,-50%,DHAK,+50%,0.039595,0.024088,0.000954,0.021088,True
18,CYOR_u6m,-25%,MDHm,+50%,NADH2_u6cm,-50%,HEX1,+50%,0.037467,0.025311,0.000948,0.022311,True
19,CYOR_u6m,-25%,SFGTH,-50%,NADH2_u6cm,-50%,HEX1,+50%,NaN,NaN,NaN,NaN,False

In [46]:
# ============================================================
# SAVE FOURTH-GENERATION 4-WAY MUTANTS
# ============================================================

fourth_generation_results.to_excel(
    "results/fourth_generation_4way_mutants.xlsx",
    index=False
)

print("Fourth-generation results saved to:")
print("results/fourth_generation_4way_mutants.xlsx")

Fourth-generation results saved to:
results/fourth_generation_4way_mutants.xlsx